// Zara Discovery Calculus v2: Learning + Practice with embedded book pages.
(function(){
  const EX={
    graph:{example:'Compare y=x², y=x²+2 and y=(x-2)². The first change moves the graph up; the second moves it right.',why:'Changing one parameter at a time makes graph transformations visible.',watch:'Predict before graphing so the tool checks thinking rather than replacing it.'},
    limits:{example:'For (x²-4)/(x-2), values near x=2 approach 4 even though direct substitution gives 0/0.',why:'A limit describes nearby behaviour, not necessarily the function value at the target.',watch:'Approach from both sides and distinguish “undefined at” from “has no limit”.'},
    zoom:{example:'Near a smooth point on y=x², enough zoom makes the curve look line-like; at the corner of y=|x| it does not settle to one slope.',why:'Differentiability is local linear behaviour.',watch:'A picture that merely looks smooth at one zoom level is evidence, not proof.'},
    derivative:{example:'For f(x)=x² at x=2, secant slopes over h=.5,.1,.01 move toward 4.',why:'The derivative is the limiting slope of secant lines as the second point approaches.',watch:'Keep x fixed while h shrinks.'},
    ivt:{example:'A continuous function going from -2 to 5 must pass through 0 somewhere in between.',why:'A continuous graph cannot jump over an intermediate height.',watch:'The theorem needs continuity on the interval.'},
    fprime:{example:'Where f rises, f′ is positive; at a smooth local maximum f′=0; where f falls, f′ is negative.',why:'The derivative records local slope.',watch:'A horizontal tangent does not automatically mean a maximum or minimum.'},
    chain:{example:'For y=(3x+1)²: outside u² gives 2u; inside 3x+1 gives 3; combine -> 6(3x+1).',why:'A change in x passes through the inside function and then the outside function.',watch:'Name the layers before differentiating.'},
    sensitivity:{example:'If a 0.01 change in x changes output by about 0.5, the local sensitivity is about 50.',why:'Derivative size measures output change per unit input change locally.',watch:'Keep units attached; sensitivity depends on scale.'},
    newton:{example:'For x²-2=0, start x=1.5; tangent-line intercept gives a better approximation to √2.',why:'Near the root, the tangent line approximates the curve and is easy to solve.',watch:'A poor starting guess can fail or converge to an unexpected root.'},
    lhopital:{example:'sin x/x at x→0 is 0/0, so it is an indeterminate quotient candidate for l’Hôpital after the prerequisites are in place.',why:'The rule compares relative rates of numerator and denominator near the point.',watch:'Never apply it before checking for an indeterminate form.'},
    riemann:{example:'Area under y=x from 0 to 2 is approximated by rectangles; narrower rectangles bring the sum toward 2.',why:'The definite integral is the limit of increasingly fine area sums.',watch:'Be clear whether rectangle heights use left, right or midpoint values.'},
    accumulation:{example:'A(x)=area under y=t from 0 to x grows faster near x=3 than x=1 because the current graph height is larger.',why:'The derivative of accumulated area reflects the current height of the original function.',watch:'Area accumulated can keep increasing even while its rate of increase changes.'},
    averagevalue:{example:'If a function is 2 for half the interval and 6 for half, the equal-area constant height is 4.',why:'Average value is the rectangle height with the same width and total area.',watch:'Do not average endpoint values unless the situation justifies it.'},
    arclength:{example:'Replace a curve by a few straight chords, total their lengths, then repeat with more shorter chords.',why:'Finer polygonal approximations track the curve more closely.',watch:'Arc length is not the horizontal width or vertical change.'},
    mystery:{example:'Collect properties - symmetry, area behaviour, derivative behaviour, transformations - before naming the function.',why:'A function can be identified from a sufficiently rich set of constraints.',watch:'Do not jump to a familiar formula after one clue.'},
    exponential:{example:'Among a^x graphs, one special base has local growth rate matching its own value.',why:'The exponential function e^x is characterized by derivative equal to itself.',watch:'Separate observed numerical evidence from the later formal proof.'},
    integralpatterns:{example:'Compare several antiderivatives of related integrands and look for what changes systematically while +C remains arbitrary.',why:'Families of integrands often reveal reusable integration structures.',watch:'Pattern recognition suggests a rule; verify by differentiating.'},
    numericalint:{example:'Approximate one region using rectangles, trapezoids and Simpson-style parabolic pieces with the same subinterval count.',why:'Different local shapes approximate curvature with different accuracy.',watch:'Compare methods under the same interval partition.'},
    sequences:{example:'Plot terms of 1/n, (-1)^n and n²: one settles to 0, one oscillates, one grows without bound.',why:'A sequence is a function on whole-number inputs; its long-run behaviour can be seen in its terms.',watch:'Oscillation and divergence are different behaviours.'},
    series:{example:'For 1+1/2+1/4+..., track partial sums 1,1.5,1.75,1.875,... approaching 2.',why:'An infinite series is understood through the sequence of its finite partial sums.',watch:'Individual terms going to 0 is necessary but not sufficient for convergence.'},
    comparison:{example:'If a_n/b_n approaches a positive finite constant and one positive series converges, the other has the same convergence behaviour.',why:'The terms are eventually comparable up to a constant factor.',watch:'The ratio must approach a positive finite nonzero constant for the standard test.'},
    polynomialapprox:{example:'Near x=0, a low-degree polynomial can imitate a smooth function closely; farther away the approximation may drift.',why:'Matching local derivative information creates increasingly accurate local models.',watch:'An approximation is local unless its error is controlled more broadly.'},
    radius:{example:'Partial sums of a power series behave well near the centre and may fail beyond a boundary distance.',why:'Power series convergence is organized by distance from the centre.',watch:'Endpoints often need separate tests.'},
    polar:{example:'A polar point is made by turning to angle θ and moving distance r; negative r reverses direction.',why:'Polar coordinates encode direction and distance rather than horizontal/vertical displacement.',watch:'The same point can have many polar representations.'},
    euler:{example:'From a known point, use the current slope for one small horizontal step, then recompute the slope and repeat.',why:'A differential equation gives local direction; Euler stitches local linear steps into an approximate solution.',watch:'Large step sizes accumulate more error.'},
    surfaces:{example:'A bowl-shaped surface has U-shaped vertical slices in both x and y directions; cross-sections constrain the 3D shape.',why:'A surface can be reconstructed conceptually from families of 2D slices.',watch:'One set of slices may not uniquely identify the surface.'}
  };
  let current=null,Q=null;
  function d(l){return EX[l.type]||{example:'Use the embedded lab example and narrate the experiment before formalizing it.',why:'The lab is designed to make the concept emerge from evidence and questions.',watch:'Do not replace discovery with a formula before Zara has described the pattern.'};}
  function embed(l){const u=calcPdf(l);return `<div class="source-embed"><div class="source-head"><div><div class="label">SOURCE LAB</div><strong>${calcPages(l)}</strong></div><a class="small-btn" href="${u}" target="_blank" rel="noopener">Open full screen</a></div><iframe class="source-frame" src="${u}#page=1&view=FitH" title="${l.title}" loading="lazy"></iframe></div>`;}
  function tabs(l,a){return `<div class="lesson-tabs"><button data-ctab="learn" class="lesson-tab ${a==='learn'?'active':''}">Learning</button><button data-ctab="practice" class="lesson-tab ${a==='practice'?'active':''}">Practice</button></div>`;}
  function wire(l){screen.querySelectorAll('[data-ctab]').forEach(b=>b.onclick=()=>renderLab(l.id,b.dataset.ctab));}
  function home(){homeBtn.onclick=renderProfiles;screen.innerHTML=`<div class="crumbs"><button class="text-link" id="cb">Math profiles</button><span>›</span><span>Discovery Calculus</span></div><div class="eyebrow">ZARA · LEARNING BY DISCOVERY</div><h2>Discovery Calculus</h2><p class="lead">Learn from the experiment first, with the actual lab pages visible. Practice is separate and asks Zara to predict, test and explain rather than simply copy a procedure.</p><div class="lesson-list">${CALC_LABS.map(l=>{const p=cp(l.id);return `<button class="lesson-tile" data-cl="${l.id}"><div><strong>${l.n}. ${l.title}</strong><span>${calcPages(l)}</span></div><span class="status ${p.secure?'mastered':''}">${p.secure?'Secure':p.attempts?`Level ${p.level}`:'Not started'}</span></button>`}).join('')}</div>`;document.getElementById('cb').onclick=renderProfiles;screen.querySelectorAll('[data-cl]').forEach(b=>b.onclick=()=>renderLab(b.dataset.cl,'learn'));}
  function renderLab(id,tab='learn'){const l=CALC_LABS.find(x=>x.id===id),p=cp(id),e=d(l);current=l;if(tab==='learn'){screen.innerHTML=`<div class="eyebrow">LAB ${l.n} · ${readinessLabel(l.readiness)}</div><h2>${l.title}</h2>${tabs(l,'learn')}<div class="learn-card"><div class="label">WHAT THIS LAB IS TRYING TO DISCOVER</div><p>${l.goal}</p></div><div class="learn-card"><div class="label">READINESS</div><p>${l.timing}</p></div><div class="learn-card"><div class="label">SET UP</div><p>${l.materials}</p></div><div class="learn-card"><div class="label">HOW TO RUN IT</div><p>${l.doit}</p></div><div class="worked-example"><div class="label">WORKED / GUIDED EXAMPLE · OURS, SAME IDEA</div><p>${e.example}</p></div><div class="learn-grid"><div class="learn-card"><div class="label">WHY IT MATTERS</div><p>${e.why}</p></div><div class="learn-card"><div class="label">WATCH FOR</div><p>${e.watch}</p></div></div><div class="card soft"><div class="label">ASK ZARA</div><p class="script"><strong>${l.say}</strong></p></div>${embed(l)}<div class="actions"><button id="cprac" class="primary">Go to practice</button></div>`;wire(l);document.getElementById('cprac').onclick=()=>renderLab(l.id,'practice');}else{screen.innerHTML=`<div class="eyebrow">LAB ${l.n}</div><h2>${l.title}</h2>${tabs(l,'practice')}<div class="mastery-line"><strong>Level ${p.level}/4</strong><span>${p.streak||0}/2 confident explanations</span></div><div class="card soft"><div class="label">PRACTICE MODE</div><p class="script">Zara predicts first, then graphs/calculates/experiments, then explains what the evidence means. The source lab stays available separately.</p></div><div class="actions"><button id="cq" class="primary">Give me an exploration</button><button id="csource" class="secondary">Use the source lab</button><button id="clearn" class="quiet">Back to learning</button></div>`;wire(l);document.getElementById('cq').onclick=()=>question(l,p.level);document.getElementById('csource').onclick=()=>source(l);document.getElementById('clearn').onclick=()=>renderLab(l.id,'learn');}}
  function question(l,level){Q=calcQuestion(l,level);screen.innerHTML=`<div class="eyebrow">${l.title} · Level ${level}</div>${tabs(l,'practice')}<div class="question-box"><div class="label">ASK ZARA</div><div class="q">${Q.text}</div></div><div class="reveal-row"><button id="chint" class="secondary">Show hint</button><button id="cans" class="quiet">Show parent answer</button></div><div id="chb"></div><div id="cab"></div><div class="actions"><button id="crecord" class="primary">Record what happened</button></div>`;wire(l);document.getElementById('chint').onclick=()=>document.getElementById('chb').innerHTML=`<div class="card soft"><p class="script">${Q.hint||l.say}</p></div>`;document.getElementById('cans').onclick=()=>document.getElementById('cab').innerHTML=`<div class="card"><div class="label">PARENT ANSWER</div><p class="script"><strong>${Q.answer}</strong></p></div>`;document.getElementById('crecord').onclick=()=>outcomes(l);}
  function source(l){screen.innerHTML=`<div class="eyebrow">${l.title} · Source lab</div>${tabs(l,'practice')}<div class="card soft"><p class="script">Use the next relevant experiment/question in the actual lab. Ask Zara for a prediction before she uses the calculator or graphing tool.</p></div>${embed(l)}<div class="actions"><button id="csr" class="primary">Record what happened</button></div>`;wire(l);document.getElementById('csr').onclick=()=>outcomes(l);}
  function outcomes(l){screen.innerHTML=`<div class="eyebrow">${l.title}</div><h2>What happened?</h2><div class="outcomes"><button data-co="confident"><strong>Got it + could explain</strong></button><button data-co="help"><strong>Got it after a prompt</strong></button><button data-co="idea"><strong>Graph/table right, explanation shaky</strong></button><button data-co="notation"><strong>Lost in the notation</strong></button><button data-co="prereq"><strong>Prerequisite gap</strong></button><button data-co="different"><strong>Different valid insight</strong></button><button data-co="wrong"><strong>Wrong / unsure</strong></button></div>`;screen.querySelectorAll('[data-co]').forEach(b=>b.onclick=()=>intervene(l,b.dataset.co));}
  function record(l,o){const p=cp(l.id);p.attempts=(p.attempts||0)+1;p.streak=p.streak||0;let ev='stay';if(o==='confident'){p.streak++;if(p.streak>=2){if((p.level||1)<4){p.level++;p.streak=0;ev='levelup'}else{p.secure=true;p.streak=0;ev='secure'}}}else p.streak=0;calcSave();return ev;}
  function intervene(l,o){const ev=record(l,o),p=cp(l.id);let t='',b='',tone='';if(o==='confident'){if(ev==='secure'){t='Secure for this exploration';b='Two confident explanations at Level 4. Stop here; this is not a claim of full calculus-course mastery.';tone='good'}else if(ev==='levelup'){t=`Move to Level ${p.level}`;b='Increase independence: less prompting, more prediction, or a transfer example.';tone='good'}else{t='One confirming exploration';b='Ask one more at this level before moving up.'}}if(o==='help'){t='Stay here';b='Repeat the same conceptual move with one fewer prompt.'}if(o==='idea'){t='Return to the evidence';b='The graph/table may be correct, but ask Zara what pattern the evidence supports before introducing formal language.';tone='warn'}if(o==='notation'){t='Strip away notation';b='Return to the graph, table, motion, area or geometric picture. Reintroduce symbols only after the idea can be said in ordinary language.';tone='warn'}if(o==='prereq'){t='Stop and bridge the prerequisite';b=`Use the lab's readiness note: ${l.timing}`;tone='warn'}if(o==='different'){t='Keep the insight';b='If Zara’s conjecture is mathematically valid, follow it. Compare it with the lab’s intended route afterward.'}if(o==='wrong'){t='Find the first break';b='Ask: Did the setup match the question? Was the prediction clear? Was the graph/table/calculation interpreted correctly? Repair the first failure only.';tone='warn'}screen.innerHTML=`<div class="eyebrow">NEXT PARENT MOVE</div><h2>${t}</h2><div class="result ${tone}"><div class="route-title">${t}</div><p class="route-copy">${b}</p></div><div class="toolbar"><button id="cl" class="secondary">Learning</button>${p.secure?'<button id="ch" class="primary">Back to labs</button>':`<button id="cp" class="primary">${ev==='levelup'?`Try Level ${p.level}`:'Practice again'}</button>`}</div>`;document.getElementById('cl').onclick=()=>renderLab(l.id,'learn');let x=document.getElementById('cp');if(x)x.onclick=()=>renderLab(l.id,'practice');let h=document.getElementById('ch');if(h)h.onclick=home;}
  window.renderCalculusHome=home;
})();