// Zara Terry Chew v2: explicit Learning + Practice with embedded source pages.
// Uses the existing book/chapter map and PDF excerpt endpoint from olympiad.js.
(function(){
  const DETAILS={
    time:{idea:'Treat time as movement along a timeline, not as a separate kind of arithmetic.',steps:['Mark the starting time.','Break the elapsed time into friendly chunks such as whole hours, 30 minutes, 15 minutes or 5 minutes.','Move one chunk at a time and keep the new time visible.','Check whether you crossed an hour boundary.'],example:'2:35 + 50 min -> +25 min = 3:00, then +25 min = 3:25.',why:'Crossing an hour becomes ordinary chunking instead of a special clock trick.',watch:'Do not add minutes as if 60 were 100.'},
    intervals:{idea:'Planting-tree problems are usually about the number of gaps, not just the number of objects.',steps:['Draw or place the objects in a row.','Count the intervals between neighbouring objects.','For an open line: intervals = objects - 1.','For a closed loop: intervals = objects.','Multiply interval count by spacing when finding total length.'],example:'6 trees in a straight row, 4 m apart -> 5 intervals -> 5 x 4 = 20 m.',why:'The first and last object create no extra gap beyond the ends.',watch:'Decide first whether the arrangement is open or closed.'},
    fourops:{idea:'Rearrange arithmetic so the calculation becomes friendlier without changing its value.',steps:['Look for a nearby round number or a convenient regrouping.','Make the easy change.','Compensate for exactly what you changed.','Check by estimating the size of the answer.'],example:'398 + 247 -> 400 + 247 - 2 = 645.',why:'Equivalent expressions let you choose the form that is easiest to calculate.',watch:'Compensation must undo the exact change you made.'},
    replace:{idea:'If one combination is known to equal another, replace it so there are fewer unknown kinds to reason about.',steps:['Write the two relationships clearly.','Find a group in one relationship that is equivalent to a group in the other.','Replace that group.','Solve the simpler one-type relationship, then work back if needed.'],example:'If 2 triangles = 1 square and 3 squares = 18, then 6 triangles = 18, so 1 triangle = 3.',why:'Replacement preserves value while reducing the number of unknowns.',watch:'Replace equal groups, not merely equal numbers of symbols.'},
    age:{idea:'Age differences stay constant even though everyone gets older.',steps:['Write both current ages on parallel timelines.','Record the age difference.','Move both people forward or backward by the same number of years.','Use the unchanged difference to solve the target age.'],example:'Zara is 10 and a cousin is 4 years older. When Zara is 13, cousin is 17.',why:'Both ages increase one year per year, so the gap never changes.',watch:'Ratios of ages do change; differences do not.'},
    division:{idea:'Division can mean sharing into a known number of groups or making groups of a known size.',steps:['Ask which quantity is unknown: group size or number of groups.','Model the groups if needed.','Use the related multiplication fact.','Check by multiplying quotient x divisor.'],example:'24 ÷ 6 asks: how many groups of 6 fit in 24? Since 4 x 6 = 24, answer 4.',why:'Multiplication and division describe the same equal-group structure from different directions.',watch:'Do not mix up number of groups with amount in each group.'},
    chicken:{idea:'Assume every animal is the simpler type, measure the error, then use the fixed per-animal difference to correct it.',steps:['Count total animals.','Pretend all are the type with fewer legs.','Compute the pretend number of legs.','Find the difference from the real total.','Each replacement changes the leg count by a fixed amount; divide the error by that amount.'],example:'10 chickens/rabbits, 28 legs. All chickens -> 20 legs. Error 8. Each rabbit adds 2 legs, so 4 rabbits and 6 chickens.',why:'Every swap from chicken to rabbit changes the total by exactly 2 legs.',watch:'The correction size is the difference between the two types, not the larger number of legs.'},
    assuming:{idea:'Assume all items are one type, then correct the total using the fixed difference between types.',steps:['Assume all items are type A.','Calculate the total under that assumption.','Compare with the actual total.','Find how much one replacement changes the total.','Error ÷ change per replacement = number that must be switched.'],example:'8 tickets are either Rs10 or Rs15 and total Rs100. All Rs10 -> Rs80. Error Rs20. Each switch adds Rs5, so 4 tickets are Rs15.',why:'The total error accumulates in equal-sized corrections.',watch:'Choose an assumption that makes the correction direction easy to interpret.'},
    pattern:{idea:'A pattern rule must explain every shown term, not just produce a plausible next number.',steps:['Compare neighbouring terms.','Write the first differences or transformations.','If those changes vary, inspect the pattern of the changes.','State the rule in words.','Test it against all given terms before predicting.'],example:'3, 6, 10, 15, 21: differences are +3,+4,+5,+6, so next is +7 -> 28.',why:'Looking at the changes often reveals structure hidden in the terms themselves.',watch:'Many short sequences allow multiple rules; prefer the simplest rule supported by all given information.'},
    counting:{idea:'Systematic counting prevents both omissions and double-counting.',steps:['Decide what counts as one object/case.','Choose an ordering rule: by size, start point, orientation, first choice, etc.','Count one category completely.','Record its subtotal.','Move to the next category and verify no overlap.'],example:'Handshakes among 5 people: first person 4, next adds 3 new, then 2, then 1 -> 10.',why:'An organized list turns a visual or combinatorial problem into disjoint cases.',watch:'If two categories can overlap, the count is not yet safe.'},
    logic:{idea:'Treat every clue as a constraint and eliminate impossible assignments before guessing.',steps:['Create a small table or set of possibilities.','Enter direct facts first.','Use each negative clue to cross out impossibilities.','Whenever only one option remains in a row/column, lock it in.','Repeat until the puzzle resolves.'],example:'Three children choose red, blue, green once each. Ben=blue; Asha not red; Chen not green -> Asha=green, Chen=red.',why:'Each deduction shrinks the space of possible solutions.',watch:'Do not treat “not X” as evidence for one specific alternative when several remain.'},
    listing:{idea:'Make a list or table in a fixed order so you know when every case has been included.',steps:['Fix the first choice.','List every possible second choice with it.','Then change the first choice once and repeat.','Count only after the list is complete.'],example:'3 shirts and 2 trousers -> A1,A2,B1,B2,C1,C2 -> 6 outfits.',why:'A structured list is both a solution method and a proof of completeness.',watch:'Random listing easily creates repeats.'},
    model:{idea:'Translate the words into bars or blocks so the relationships are visible before choosing operations.',steps:['Draw one bar for each compared quantity.','Align equal parts.','Mark the known total, difference or ratio parts.','Find the value of one common part.','Use it to recover each requested quantity.'],example:'Two numbers total 50 and one is 10 more. Remove the extra 10 -> 40 split equally -> 20 and 30.',why:'The model exposes the invariant equal parts hidden by the wording.',watch:'Label what every bar represents; unlabeled bars become decoration.'},
    series:{idea:'Look for a grouping that repeats the same total.',steps:['Write the first and last terms together.','Pair inward.','Check whether each pair has the same sum.','Count the pairs; handle a middle term separately if there is one.'],example:'1+2+...+10 -> (1+10),(2+9)... = five pairs of 11 -> 55.',why:'Symmetric pairing converts many additions into one multiplication.',watch:'Odd numbers of terms leave one unpaired middle term.'},
    gauss:{idea:'Pair terms from opposite ends of an arithmetic sequence so every pair has the same sum.',steps:['Find first term, last term and number of terms.','Pair first+last, second+second-last, etc.','Multiply pair sum by number of pairs.','If there is a middle term, include it once.'],example:'1 to 20 -> pair sum 21, 10 pairs -> 210.',why:'Arithmetic sequences have constant spacing, so symmetric pairs have equal sums.',watch:'Count terms carefully when the sequence does not start at 1.'},
    next:{idea:'In visual sequences, track transformations such as rotation, movement, alternation, count change or shading.',steps:['Compare frame 1 to frame 2.','Name exactly what changed.','Check whether the same change explains frame 2 to frame 3.','Also note what stays invariant.','Only then choose the next figure.'],example:'Use the embedded Terry Chew figure. State the transformation before selecting an answer.',why:'Naming the transformation is more reliable than visual guessing.',watch:'Some puzzles combine two simultaneous patterns.'},
    iq:{idea:'Find a single relation that explains all rows, boxes or figures before applying it to the missing value.',steps:['Pick one complete example.','Test a simple operation or positional rule.','Check it against every other complete example.','Reject any rule that fails once.','Apply the surviving rule to the missing case.'],example:'Use the embedded source diagram; first turn one complete row into an equation.',why:'The completed examples are constraints on the hidden rule.',watch:'Do not invent a different rule for each row.'},
    geometry:{idea:'Break a complicated figure into familiar shapes, or build it from them.',steps:['Trace the outer boundary.','Identify rectangles, triangles, squares or repeated pieces.','Mark shared/internal edges separately from outer edges.','Add or subtract the simple pieces as the problem requires.'],example:'An L-shape can be treated as a large rectangle minus the missing corner rectangle.',why:'Decomposition converts an unfamiliar figure into known geometry.',watch:'Shared internal edges do not contribute to perimeter.'},
    parity:{idea:'Odd/even behaviour can solve a problem without full calculation.',steps:['Recall: even = pairs with no leftover; odd = one leftover.','Translate the operation into parity: E+E=E, O+O=E, E+O=O; products are odd only if both factors are odd.','Use the parity restriction to eliminate impossible answers.'],example:'37+58 must be odd because odd+even=odd.',why:'Parity keeps only one bit of information but that bit is often enough.',watch:'Do not confuse the parity of a sum with the parity of the number of terms.'},
    queue:{idea:'Positions from the front and back overlap at the named person.',steps:['Draw the queue as dots.','Mark the person’s position from the front.','Mark the same person from the back.','Add the two positions and subtract 1 because the person was counted twice.'],example:'Zara is 5th from front and 7th from back -> 5+7-1 = 11 people.',why:'Both counts include Zara.',watch:'If the question says people in front/behind rather than position, use front + person + behind.'},
    backwards:{idea:'Start from the final result and undo operations in reverse order.',steps:['Write the sequence of operations as arrows.','Begin at the final number.','Undo the last operation first using its inverse.','Continue backward until the starting value is recovered.','Check by running forward.'],example:'A number +5 then x3 gives 36. Undo ÷3 ->12, then -5 ->7.',why:'Function composition reverses in the opposite order.',watch:'Reverse both the operation and the order.'},
    pigeonhole:{idea:'If more objects are forced into fewer categories, some category must contain multiple objects.',steps:['Identify the “objects” and the “boxes/categories”.','Imagine spreading objects as evenly as possible.','Fill each box to the maximum allowed before a repeat.','The next object forces the desired conclusion.'],example:'13 socks in 6 colours -> at least 3 of one colour, because 2 per colour holds only 12.',why:'The extremal “spread them out” arrangement tells you what is guaranteed.',watch:'For “at least k”, test how many objects could fit while keeping every box at k-1.'},
    speed:{idea:'Speed problems connect distance, rate and equal units of time.',steps:['Draw the journey or a distance strip.','Mark what one unit of time represents.','Use distance = speed x time, or rearrange it only after the meaning is clear.','Keep units consistent.'],example:'6 km/h for 4 h -> 24 km.',why:'Speed is distance per unit time.',watch:'Minutes and hours must be converted before combining.'},
    observation:{idea:'These chapters depend on noticing structure in the actual diagram before calculating.',steps:['Use the embedded source page.','Ask Zara to describe three things she notices before solving.','Mark repeated shapes, symmetries, overlaps or hidden pieces directly on paper.','Choose a counting or transformation method only after the structure is named.'],example:'Use the first unsolved source figure; the “worked example” is the annotated source itself.',why:'The visual information is part of the mathematics and should not be replaced by a text-only imitation.',watch:'Do not reveal the intended trick before Zara has inspected the diagram.'},
    multricks:{idea:'Regroup factors to create easy products such as 10, 100 or 1000.',steps:['Factor one or both numbers when useful.','Reorder factors using commutativity/associativity.','Make a friendly product first.','Multiply the remaining factor.'],example:'32 x 25 -> 8 x 4 x 25 -> 8 x 100 = 800.',why:'The product is unchanged when factors are regrouped.',watch:'Only regroup factors in multiplication; do not move terms across addition/subtraction without justification.'},
    excess:{idea:'Two distribution scenarios create an excess and a shortage; their combined gap reveals the group size.',steps:['Write scenario A and its excess.','Write scenario B and its shortage.','Add excess + shortage to get the total gap between scenarios.','Find how much the allocation changes per person/item.','Total gap ÷ per-person change = number of people/items.'],example:'Give 4 each -> 6 left. Give 5 each -> 3 short. Gap = 9; change =1 each -> 9 people.',why:'Changing the allocation for every person accounts for the full difference between the two scenarios.',watch:'Excess and shortage are added, not subtracted, when they lie on opposite sides of the true total.'},
    catchup:{idea:'For chasing, the gap closes at the difference of the two speeds.',steps:['Draw both travelers moving in the same direction.','Mark the initial head start.','Find relative speed = faster - slower.','Time to catch = gap ÷ relative speed.'],example:'Runner A is 30 m ahead. B runs 8 m/s, A 5 m/s. Gap closes 3 m/s -> 10 s.',why:'Both move forward, so only the extra speed of the faster traveler reduces the gap.',watch:'Use speed difference only when moving in the same direction.'},
    meeting:{idea:'For two travelers moving toward each other, the gap closes at the sum of the speeds.',steps:['Draw both at opposite ends.','Mark the starting distance.','Find closing speed = speed1 + speed2.','Time to meet = distance ÷ closing speed.'],example:'60 km apart, speeds 4 and 6 km/h -> closing speed 10 -> meet in 6 h.',why:'Both movements reduce the same gap.',watch:'Do not use the sum if both are moving in the same direction.'},
    digits:{idea:'Digit problems are constraint problems about place value, allowed digits and divisibility/multiples.',steps:['Write the place-value form, e.g. 10a+b.','List the restrictions.','Apply the strongest restriction first.','Generate only candidates that survive it.','Check remaining conditions.'],example:'Two-digit multiple of 5 with digit sum 9: ones digit 0 or 5; testing gives 45 or 90 depending on other conditions.',why:'Place-value notation turns digit wording into algebraic constraints.',watch:'A digit and the number it represents in a place are different quantities.'},
    cryptarithm:{idea:'Solve letter-digit arithmetic column by column using carries as constraints.',steps:['Start with the ones column.','List possible digit sums and carry values.','Move to the tens column with that carry.','Enforce “same letter = same digit” and different-letter restrictions.','Check the complete arithmetic at the end.'],example:'Use the embedded puzzle; write the ones-column equation first, including any carry.',why:'Carries link adjacent columns and sharply restrict possibilities.',watch:'Do not guess whole numbers before exploiting column constraints.'},
    perimeter:{idea:'Perimeter is the outside boundary; shared internal edges disappear.',steps:['Trace only the outer edge with a finger/pencil.','For composite shapes, count exposed unit edges or combine known side lengths.','Ignore edges where two shapes touch.','Check that you returned to the starting point.'],example:'Two unit squares sharing one side have perimeter 6, not 8.',why:'The shared side is inside the combined figure.',watch:'Area and perimeter respond differently when shapes are joined.'},
    numberpuzzle:{idea:'Translate each local visual relationship into an equation or rule before solving the full puzzle.',steps:['Choose one complete part of the diagram.','Write the arithmetic relation it represents.','Check that relation on another complete part.','Use the confirmed rule on the unknown.'],example:'Use the embedded source diagram; convert one complete cluster into an equation first.',why:'The diagram is a compact representation of repeated local constraints.',watch:'Do not assume every number in the figure participates in the same way.'},
    journey:{idea:'Journey problems become easier when the motion is drawn before any formula is used.',steps:['Draw start and destination.','Mark direction, stops, turns or return legs.','Label known distances/times/speeds on the correct segment.','Solve one segment or gap at a time.'],example:'If 12 km is travelled out and 5 km back, net displacement is 7 km but total distance travelled is 17 km.',why:'A route diagram separates distance travelled, direction and remaining gap.',watch:'Distance and displacement are not interchangeable.'},
    cubes:{idea:'Count a 3D stack by layers or vertical columns, including cubes that are hidden in the drawing.',steps:['Use the embedded diagram or rebuild with cubes.','Identify the footprint/base positions.','For each position, determine stack height.','Add stack heights, or count layer by layer.'],example:'A 2x2 base with heights 1,2,2,3 contains 8 cubes.',why:'Every visible top cube may imply supporting cubes underneath.',watch:'Do not count only visible faces/cubes.'},
    shortest:{idea:'Count shortest paths by accumulating how many ways can arrive at each point.',steps:['Restrict moves to those allowed in a shortest path.','Write 1 at the start.','At each new point, add the path counts from all allowed predecessor points.','Continue until the destination.'],example:'On a simple grid moving only right/up, interior counts are the sum of the count from left and from below.',why:'Every path to a point must arrive through one of its immediate predecessor points.',watch:'Do not include moves that make the route longer than shortest.'},
    remainder:{idea:'Use dividend = divisor x quotient + remainder, with remainder smaller than divisor.',steps:['Identify the divisor.','Find the largest multiple not exceeding the dividend.','Subtract to get the remainder.','Check remainder < divisor.'],example:'47 ÷ 6 -> 6x7=42, remainder 5 -> 47 = 6x7+5.',why:'The quotient counts full groups and the remainder is what cannot form another full group.',watch:'A remainder equal to or larger than the divisor means another group was possible.'},
    pagenumber:{idea:'Count printed digits in blocks: 1-digit pages, 2-digit pages, 3-digit pages, etc.',steps:['Split the page range by number of digits.','Count how many page numbers lie in each block.','Multiply pages in the block by digits per page number.','Add block totals.'],example:'Pages 1-120: 9x1 + 90x2 + 21x3 = 252 digits.',why:'Every page in the same digit-length block contributes the same number of printed digits.',watch:'The block 100-120 has 21 pages, not 20.'},
    newops:{idea:'A new operation symbol is just a definition; substitute into the definition exactly.',steps:['Copy the operation definition.','Replace the placeholders with the given numbers.','Apply ordinary order of operations.','Do not invent familiar meaning for the new symbol.'],example:'If a ★ b = 2a+b, then 3 ★ 5 = 2(3)+5 = 11.',why:'The symbol has no meaning beyond the rule provided.',watch:'Keep track of which input is first and which is second.'},
    onesdigit:{idea:'For large powers/products, the ones digit often repeats in a short cycle.',steps:['Compute only the ones digit for the first few powers.','Stop when the cycle repeats.','Find the cycle length.','Use the exponent modulo the cycle length to locate the needed position.'],example:'Powers of 2 end 2,4,8,6 repeating every 4; 2^17 uses position 1 -> ones digit 2.',why:'Only the previous ones digit determines the next ones digit under repeated multiplication.',watch:'Handle exponents divisible by the cycle length as the last position in the cycle, not position 0.'},
    arithmeticseq:{idea:'A sequence with a common difference grows by the same amount each step.',steps:['Confirm the difference is constant.','Identify first term a and common difference d.','To move to term n, make n-1 jumps.','Use a+(n-1)d when a direct term is useful.'],example:'5,8,11,...; 20th term = 5 + 19x3 = 62.',why:'The first term is already term 1, so only n-1 jumps are needed.',watch:'Do not multiply the difference by n.'},
    prime:{idea:'A prime number has exactly two positive factors: 1 and itself.',steps:['Try factor pairs only up to the square root.','If none divide evenly, the number is prime.','Use divisibility tests to eliminate easy composites quickly.'],example:'29: not divisible by 2,3 or5; sqrt(29)<6, so no other prime test is needed -> prime.',why:'If n=ab and both factors exceeded sqrt(n), their product would exceed n.',watch:'1 is neither prime nor composite.'},
    divisibility:{idea:'Divisibility tests are filters that detect factors without carrying out full division.',steps:['Use last-digit tests for 2,5,10.','Use digit sum for 3 and 9.','Use last two digits for 4 when relevant.','Combine tests when the divisor factors into coprime parts.'],example:'4374: digit sum 18 -> divisible by 9; last digit even -> divisible by 2, so divisible by 18.',why:'The tests encode how powers of 10 behave modulo the divisor.',watch:'Passing tests for separate factors only guarantees the product when the factor conditions are appropriate.'},
    equations:{idea:'Translate the story into one unknown, then undo operations while keeping equality balanced.',steps:['Choose what x represents.','Write one equation from the relationship.','Undo operations using inverse operations on both sides.','Check the result in the original statement.'],example:'3x+5=20 -> 3x=15 -> x=5.',why:'Doing the same operation to both sides preserves equality.',watch:'Do not reverse operation order incorrectly when more than one operation surrounds x.'},
    average:{idea:'Average is the equal-share value of a fixed total.',steps:['Find total = average x number of items when useful.','Or add all values and divide by count.','For changes, track how the total changes before recomputing average.'],example:'Average of 4 numbers is 12 -> total 48. Add a fifth number 17 -> new average 65/5=13.',why:'An average redistributes the total equally across all items.',watch:'Average of averages is not generally valid unless group sizes are equal.'},
    area:{idea:'Find area by decomposing or rearranging into familiar shapes.',steps:['Mark dimensions.','Split the figure into rectangles/triangles or subtract a missing piece.','Find each simple area.','Add/subtract without double-counting overlap.'],example:'L-shape = 8x6 rectangle - 3x2 missing corner = 48-6=42 square units.',why:'Area is additive over non-overlapping pieces.',watch:'Use square units and distinguish area from perimeter.'},
    fraction:{idea:'Fractions must refer to equal-sized units before they can be compared or combined.',steps:['Identify the whole.','Make denominators represent the same-sized pieces using equivalent fractions.','Then compare/add/subtract numerators as appropriate.','Simplify only after the meaning is secure.'],example:'1/2 + 1/3 -> 3/6 + 2/6 = 5/6.',why:'You can only count together pieces of the same size.',watch:'Do not add denominators when adding fractions.'},
    ratio:{idea:'A ratio describes a repeatable batch of parts; scaling multiplies every part by the same factor.',steps:['Build one ratio batch.','Count total parts if a total is given.','Find value of one part.','Scale each category by the same factor.'],example:'Red:blue=3:2 and total 25 -> 5 parts, each 5 -> red 15, blue 10.',why:'Equivalent ratios are produced by multiplying every component by the same number.',watch:'3:2 has 5 total parts, not 3 or 2.'},
    percentage:{idea:'Percent means “per hundred,” then scales to the actual quantity.',steps:['Translate p% to p/100.','Find 1%, 10%, 25%, 50% or another friendly fraction when possible.','Scale to the requested percentage.','Estimate to check reasonableness.'],example:'35% of 80 -> 10%=8, 30%=24, 5%=4 -> 28.',why:'Percent is a ratio with denominator 100.',watch:'A percent greater than 100% can legitimately produce a value larger than the original.'},
    angles:{idea:'Use fixed angle totals as invariants: line 180°, point 360°, triangle 180°.',steps:['Identify which fixed total applies.','Write the known angles.','Subtract their sum from the fixed total.','Use equal-angle facts only when the diagram or geometry guarantees them.'],example:'Triangle has 48° and 67° -> third angle = 180-115 = 65°.',why:'The angle-sum invariant turns geometry into constrained arithmetic.',watch:'Do not trust apparent angle sizes in a not-to-scale diagram.'}
  };

  const FALLBACK={idea:'Identify the mathematical structure before calculating.',steps:['Read the source example carefully.','Name what is known and unknown.','Make the hidden relationship visible with a diagram, table or model.','Carry out one justified move at a time.','Check the result against the original conditions.'],example:'Use the embedded source example and narrate each move.',why:'Olympiad problems become manageable when the structure is externalized.',watch:'Do not rush to arithmetic before the relationship is clear.'};

  let current=null,currentQ=null;
  function detail(c){return DETAILS[c.type]||FALLBACK;}
  function esc(s){return String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));}
  function progress(c){return prog(c.id);}
  function saveProgress(){saveO();}
  function embed(c){const u=pdfUrl(c);return `<div class="source-embed"><div class="source-head"><div><div class="label">SOURCE PAGES</div><strong>${pages(c)}</strong></div><a class="small-btn" href="${u}" target="_blank" rel="noopener">Open full screen</a></div><iframe class="source-frame" src="${u}#page=1&view=FitH" title="${esc(c.title)} source pages" loading="lazy"></iframe></div>`;}
  function tabs(c,active){return `<div class="lesson-tabs"><button class="lesson-tab ${active==='learn'?'active':''}" data-otab="learn">Learning</button><button class="lesson-tab ${active==='practice'?'active':''}" data-otab="practice">Practice</button></div>`;}
  function wireTabs(c){screen.querySelectorAll('[data-otab]').forEach(b=>b.onclick=()=>renderChapter(c.id,b.dataset.otab));}

  function renderHome(){
    homeBtn.onclick=renderProfiles;
    screen.innerHTML=`<div class="crumbs"><button class="text-link" id="ob">Math profiles</button><span>›</span><span>Olympiad Math</span></div><div class="eyebrow">ZARA · TERRY CHEW</div><h2>Olympiad Math</h2><p class="lead">Learn the method first, with the actual book pages visible. Practice is separate so Zara is not looking at the worked solution while solving.</p><div class="unit-grid">${Object.entries(OLY_BOOKS).map(([k,b])=>{let cs=OLY_CHAPTERS.filter(c=>c.book===k),m=cs.filter(c=>progress(c).mastered).length;return `<button class="unit-tile" data-ob="${k}"><strong>${b.title}</strong><span>${b.grade} · ${b.age}</span><span class="unit-progress">${m}/${cs.length} secure</span></button>`}).join('')}</div>`;
    document.getElementById('ob').onclick=renderProfiles;
    screen.querySelectorAll('[data-ob]').forEach(x=>x.onclick=()=>renderBook(x.dataset.ob));
  }
  function renderBook(k){
    const b=OLY_BOOKS[k],cs=OLY_CHAPTERS.filter(c=>c.book===k);
    screen.innerHTML=`<div class="crumbs"><button class="text-link" id="oh">Olympiad Math</button><span>›</span><span>${b.title}</span></div><h2>${b.title}</h2><p class="lead">Choose a chapter. Learning contains the full teaching explanation and embedded source pages; Practice contains only the problem flow.</p><div class="lesson-list">${cs.map(c=>{let p=progress(c);return `<button class="lesson-tile" data-oc="${c.id}"><div><strong>${c.n}. ${c.title}</strong><span>Book pp. ${c.start}-${c.end}</span></div><span class="status ${p.mastered?'mastered':''}">${p.mastered?'Secure':p.attempts?`Level ${p.level}`:'Not started'}</span></button>`}).join('')}</div>`;
    document.getElementById('oh').onclick=renderHome;screen.querySelectorAll('[data-oc]').forEach(x=>x.onclick=()=>renderChapter(x.dataset.oc,'learn'));
  }
  function renderChapter(id,tab='learn'){
    const c=OLY_CHAPTERS.find(x=>x.id===id),d=detail(c),p=progress(c);current=c;
    if(tab==='learn'){
      screen.innerHTML=`<div class="eyebrow">${OLY_BOOKS[c.book].title} · Chapter ${c.n}</div><h2>${c.title}</h2>${tabs(c,'learn')}<div class="learn-card"><div class="label">THE IDEA</div><p>${d.idea}</p></div><div class="learn-card"><div class="label">HOW TO DO IT</div><ol class="method-steps">${d.steps.map(s=>`<li>${s}</li>`).join('')}</ol></div><div class="worked-example"><div class="label">WORKED EXAMPLE · OURS, SAME STRATEGY</div><p>${d.example}</p></div><div class="learn-grid"><div class="learn-card"><div class="label">WHY IT WORKS</div><p>${d.why}</p></div><div class="learn-card"><div class="label">WATCH FOR</div><p>${d.watch}</p></div></div>${embed(c)}<div class="actions"><button id="toPractice" class="primary">Go to practice</button></div>`;
      wireTabs(c);document.getElementById('toPractice').onclick=()=>renderChapter(c.id,'practice');
    }else{
      screen.innerHTML=`<div class="eyebrow">${OLY_BOOKS[c.book].title} · Chapter ${c.n}</div><h2>${c.title}</h2>${tabs(c,'practice')}<div class="card soft"><div class="label">PRACTICE RULE</div><p class="script">Zara sees only the problem first. Reveal a hint only if she needs it. If the chapter is visual, use an unsolved problem from the embedded source pages rather than replacing the diagram with a text-only imitation.</p></div><div class="mastery-line"><strong>Level ${p.level}/4</strong><span>${p.streak||0}/2 confident at this level</span></div><div class="actions"><button id="oq" class="primary">Give me a question</button><button id="sourcePractice" class="secondary">Use a book problem</button><button id="backLearn" class="quiet">Back to learning</button></div>`;
      wireTabs(c);document.getElementById('oq').onclick=()=>renderQuestion(c,p.level);document.getElementById('sourcePractice').onclick=()=>renderBookProblem(c);document.getElementById('backLearn').onclick=()=>renderChapter(c.id,'learn');
    }
  }
  function renderQuestion(c,l){
    currentQ=gen(c,l);
    screen.innerHTML=`<div class="eyebrow">${c.title} · Practice Level ${l}</div>${tabs(c,'practice')}<div class="question-box"><div class="label">ASK ZARA</div><div class="q">${currentQ.text}</div></div><div class="reveal-row"><button id="hintBtn" class="secondary">Show method hint</button><button id="ansBtn" class="quiet">Show parent answer</button></div><div id="hintBox"></div><div id="ansBox"></div><div class="actions"><button id="markBtn" class="primary">Record what happened</button></div>`;
    wireTabs(c);document.getElementById('hintBtn').onclick=()=>{document.getElementById('hintBox').innerHTML=`<div class="card soft"><div class="label">METHOD HINT</div><p class="script">${currentQ.hint||detail(c).steps[0]}</p></div>`};document.getElementById('ansBtn').onclick=()=>{document.getElementById('ansBox').innerHTML=`<div class="card"><div class="label">PARENT ANSWER</div><p class="script"><strong>${currentQ.answer}</strong></p></div>`};document.getElementById('markBtn').onclick=()=>renderOutcomes(c);
  }
  function renderBookProblem(c){
    screen.innerHTML=`<div class="eyebrow">${c.title} · Source practice</div>${tabs(c,'practice')}<div class="card soft"><div class="label">USE THE ACTUAL DIAGRAM / QUESTION</div><p class="script">Choose the next unsolved problem on these pages. Before Zara calculates, ask: <strong>“What structure do you notice, and what could we represent?”</strong></p></div>${embed(c)}<div class="actions"><button id="markBook" class="primary">Record what happened</button></div>`;wireTabs(c);document.getElementById('markBook').onclick=()=>renderOutcomes(c);
  }
  function renderOutcomes(c){
    screen.innerHTML=`<div class="eyebrow">${c.title}</div><h2>What happened?</h2><div class="outcomes"><button data-v2o="confident"><strong>Right + confident</strong><span class="mini">She could explain the strategy.</span></button><button data-v2o="help"><strong>Right, but needed help</strong></button><button data-v2o="idea"><strong>Answer right, strategy shaky</strong></button><button data-v2o="lost"><strong>Lost track midway</strong></button><button data-v2o="different"><strong>Different valid method</strong></button><button data-v2o="wrong"><strong>Wrong / unsure</strong></button></div>`;screen.querySelectorAll('[data-v2o]').forEach(b=>b.onclick=()=>intervene(c,b.dataset.v2o));
  }
  function record(c,out){
    const p=progress(c);p.attempts=(p.attempts||0)+1;p.streak=p.streak||0;let ev='stay';
    if(out==='confident'){p.streak++;if(p.streak>=2){if((p.level||1)<4){p.level=(p.level||1)+1;p.streak=0;ev='levelup'}else{p.mastered=true;p.streak=0;ev='mastered'}}}else p.streak=0;saveProgress();return ev;
  }
  function intervene(c,out){
    const d=detail(c),ev=record(c,out),p=progress(c);let title='',body='',tone='';
    if(out==='confident'){if(ev==='mastered'){title='Secure for now';body='Two confident explanations at Level 4. Stop drilling this chapter and move on; revisit it later in mixed Olympiad work.';tone='good'}else if(ev==='levelup'){title=`Move to Level ${p.level}`;body='Two confident answers were enough. The next problem should require a little more independence or a less obvious structure.';tone='good'}else{title='One confirming problem';body='Ask one more at this level. Two confident explanations move Zara up.'}}
    if(out==='help'){title='Stay at this level';body='Use the same structure again. Keep the representation, but remove one prompt.'}
    if(out==='idea'){title='Return to Learning';body='The arithmetic may be right, but the strategy is not secure. Re-open the worked example and source diagram, then ask Zara to explain why each move is allowed.';tone='warn'}
    if(out==='lost'){title='Externalize the steps';body='Keep every intermediate quantity, case or diagram mark visible. Zara should make only one transformation at a time.';tone='warn'}
    if(out==='different'){title='Keep the valid route';body='Have Zara explain why her method works. If it is valid, keep it. Then compare it with the Terry Chew strategy as a second route rather than correcting her for choosing differently.'}
    if(out==='wrong'){title='Find the first break';body='Check in this order: Can she represent the problem? Can she name the relationship? Can she make the first justified move? Can she keep the intermediate result? The first “no” is where you reteach.';tone='warn'}
    screen.innerHTML=`<div class="eyebrow">NEXT PARENT MOVE</div><h2>${title}</h2><div class="result ${tone}"><div class="route-title">${title}</div><p class="route-copy">${body}</p></div><div class="toolbar"><button id="learnAgain" class="secondary">Learning</button>${p.mastered?'<button id="bookBack" class="primary">Back to book</button>':`<button id="practiceAgain" class="primary">${ev==='levelup'?`Try Level ${p.level}`:'Practice again'}</button>`}</div>`;document.getElementById('learnAgain').onclick=()=>renderChapter(c.id,'learn');let pa=document.getElementById('practiceAgain');if(pa)pa.onclick=()=>renderChapter(c.id,'practice');let bb=document.getElementById('bookBack');if(bb)bb.onclick=()=>renderBook(c.book);
  }

  window.renderOlympiadHome=renderHome;
})();