// Terry Chew Olympiad Math parent-coach profile
const OLY_KEY='mayaOlympiadIntervention.v1';
const OLY_BOOKS={
 J1:{title:'Junior 1',age:'Ages 7–8',grade:'Primary 1–2',id:'1XOS-XNXcihLAE0QVc-RJTcMSZkbXSr_G',offset:4,last:183},
 J2:{title:'Junior 2',age:'Ages 8–9',grade:'Primary 2–3',id:'1wVNOK7mqSNfuNbQe_HGl4wZNO2LedQCa',offset:4,last:211},
 B:{title:'Beginner',age:'Ages 9–10',grade:'Primary 3–4',id:'12xakGvBuc_u6z7z2DtXabzEHXPrxlaBy',offset:7,last:207},
 I:{title:'Intermediate',age:'Ages 10–12',grade:'Primary 4–5',id:'1WM2ZpfHV57l8j2CoGRi-9-yIP4AqP4hf',offset:7,last:244}
};
const RAW={
J1:[[1,'Tell Me the Time!',1,'time'],[2,'Problems from Planting Trees – Intervals',10,'intervals'],[3,'Addition',20,'fourops'],[4,'Solve by Comparison and Replacement',26,'replace'],[5,'Age Problems',35,'age'],[6,'Division',44,'division'],[7,'Chicken-and-Rabbit Problems',55,'chicken'],[8,'Looking for a Pattern',64,'pattern'],[9,'Counting',72,'counting'],[10,'Logic',80,'logic'],[11,'Make a List, Make a Table',88,'listing'],[12,'Using Model',97,'model'],[13,'In Search of a Series',105,'series'],[14,'What Comes Next?',117,'next'],[15,'IQ Maths',124,'iq'],[16,'Geometry',132,'geometry'],[17,'Odd and Even Numbers',141,'parity'],[18,'Queuing Problems',148,'queue'],[19,'Working Backwards',154,'backwards'],[20,'Pigeonhole Principle',161,'pigeonhole'],[21,'Simple Speed',167,'speed'],[22,'Observation',174,'observation']],
J2:[[1,'Looking for a Pattern',1,'pattern'],[2,'The Story of Gauss',10,'gauss'],[3,'Using Model',19,'model'],[4,'Problems with Planting Trees',30,'intervals'],[5,'Solve by Comparison and Replacement',41,'replace'],[6,'Counting',51,'counting'],[7,'Tricks in Addition and Subtraction',58,'fourops'],[8,'Tricks in Multiplication',66,'multricks'],[9,'Age Problems',76,'age'],[10,'Working Backwards',88,'backwards'],[11,'Chicken-and-Rabbit Problems',97,'chicken'],[12,'Logic',106,'logic'],[13,'Make a List',116,'listing'],[14,'Excess-and-Shortage Problems',126,'excess'],[15,'IQ Maths',133,'iq'],[16,'Catching Up',145,'catchup'],[17,'Encountering',153,'meeting'],[18,'Digits, Numbers and Multiples',162,'digits'],[19,'Cryptarithm',172,'cryptarithm'],[20,'Perimeter of Squares and Rectangles',180,'perimeter'],[21,'Observation',190,'observation'],[22,'Number Puzzles',201,'numberpuzzle']],
B:[[1,'Looking for a Pattern',1,'pattern'],[2,'The Story of Gauss',10,'gauss'],[3,'Working Backwards',18,'backwards'],[4,'The Chicken-and-Rabbit Problem',29,'chicken'],[5,'Problems from Planting Trees',41,'intervals'],[6,'Tricks in Addition and Subtraction',51,'fourops'],[7,'Tricks in Multiplication and Division',59,'multricks'],[8,'Logic',70,'logic'],[9,'Counting',85,'counting'],[10,'Problem on Journey',91,'journey'],[11,'The Age Problem',99,'age'],[12,'Solve Using Model',111,'model'],[13,'Solve by Comparison and Replacement',124,'replace'],[14,'The Excess-and-Shortage Problem',133,'excess'],[15,'Finding Cubes',140,'cubes'],[16,'The Shortest Path',144,'shortest'],[17,'Interesting Remainder Problems',155,'remainder'],[18,'Finding Perimeter',164,'perimeter'],[19,'The Page-Number Problem',172,'pagenumber'],[20,'Defining New Operations',181,'newops'],[21,'Value of Ones Digit',188,'onesdigit'],[22,'Pigeonhole Principle',199,'pigeonhole']],
I:[[1,'The Four Operations',1,'fourops'],[2,'Solve by Assuming',13,'assuming'],[3,'Looking for a Pattern',21,'pattern'],[4,'Age Problems',27,'age'],[5,'Make a List',34,'listing'],[6,'Working Backwards',45,'backwards'],[7,'Excess-and-Shortage Problems',51,'excess'],[8,'Sequence with a Common Difference',60,'arithmeticseq'],[9,'Prime Numbers',68,'prime'],[10,'Divisibility',80,'divisibility'],[11,'Other Operations',94,'newops'],[12,'Logic',102,'logic'],[13,'Write Simple Equations',111,'equations'],[14,'The Remainder Problems',121,'remainder'],[15,'Problems from Page Numbers',132,'pagenumber'],[16,'Average Problems',141,'average'],[17,'Area',151,'area'],[18,'Fraction',162,'fraction'],[19,'Pigeonhole Principle',173,'pigeonhole'],[20,'Square Numbers and Value of Ones Digit',185,'onesdigit'],[21,'Ratio',200,'ratio'],[22,'Speed',210,'speed'],[23,'Percentage',220,'percentage'],[24,'Angles and Triangles',231,'angles']]
};
const OLY_CHAPTERS=[];Object.entries(RAW).forEach(([book,rows])=>rows.forEach((r,i)=>{let[n,title,start,type]=r,end=i<rows.length-1?rows[i+1][2]-1:OLY_BOOKS[book].last;OLY_CHAPTERS.push({id:`${book.toLowerCase()}-${n}`,book,n,title,start,end,type})}));
const STR={
 time:['Use a clock as a timeline for elapsed time.','Teaching clock.','Keep the start time visible; move only the elapsed amount.','Where do we start, how far do we move, where do we land?','Use whole hours, half-hours, then 5-minute steps.'],
 intervals:['Distinguish objects from the gaps between them.','Counters/sticks and string.','Build a row; count objects, then spaces. Compare open and closed arrangements.','Are we counting trees or spaces?','Use 4 counters: 4 objects but 3 gaps.'],
 fourops:['Reshape a calculation without changing its value.','Base-ten blocks or number cards.','Look for friendly numbers, compensation, regrouping or distribution.','Can we make this friendlier without changing the answer?','Use two-digit numbers and make a multiple of 10.'],
 replace:['Replace an equivalent group to reduce unknowns.','Two colors of counters.','Build both relationships, then swap a known-equivalent group into the other.','What group can we replace with something we know?','Start with 2 stars = 1 square.'],
 age:['Use the fact that age differences stay fixed.','Two parallel timelines.','Move both ages forward/back by the same amount.','What changes with time? What stays the same?','Use siblings 3 years apart.'],
 division:['See division as sharing/grouping and check with multiplication.','Counters and bowls.','Decide whether finding groups or group size; build it.','How many groups, or how many in each group?','Use exact divisions under 12.'],
 chicken:['Assume all items are one type, then correct by the fixed difference.','Counters with two labels.','Pretend all are chickens; measure the error; each rabbit replacement fixes 2 legs.','What if they were all chickens?','Use 5 animals and small leg totals.'],
 assuming:['Assume all items are one type/value, measure the error, then correct.','Counters and two labels.','Make the assumption explicit; divide total error by correction per replacement.','If they were all this type, how far off?','Use types differing by 1 or 2.'],
 pattern:['Describe the rule between terms, not just the next answer.','Number cards.','Write differences; if differences change, inspect their pattern too.','What changes each time? Is the change changing?','Use constant +2/+3/×2 first.'],
 counting:['Count systematically so nothing is missed or repeated.','Grid paper/tiles.','Organize by size, start point, orientation or category; record subtotals.','How will we prove we counted each exactly once?','Count one category at a time.'],
 logic:['Use clues as constraints and eliminate impossible cases.','Simple grid/table.','Record definite facts and cross out impossibilities.','What can this clue rule out immediately?','Use 3 people and 3 choices.'],
 listing:['Generate cases in an orderly way and know when the list is complete.','Paper/table.','Fix one choice and exhaust all remaining choices before moving on.','What order stops repeats and omissions?','Use two choices with 2–3 options.'],
 model:['Turn a word problem into visible parts, wholes and differences.','Paper strips/bar model.','Draw quantities before choosing an operation; align equal parts.','What does each bar represent?','Use one whole split into two parts.'],
 series:['Group terms to exploit repeated structure.','Number cards.','Look for equal-sum pairs or repeating blocks.','Can we group these so the same thing keeps happening?','Use 1+2+3+4+5.'],
 gauss:['Pair opposite terms to create equal sums.','Number cards 1–10.','Pair first+last, second+second-last; count equal pairs.','What do the outside pairs have in common?','Pair 1–10 physically.'],
 next:['Track what moves, rotates, appears or alternates.','Pattern blocks/sketches.','Compare successive frames and name change + invariant.','What changed? What stayed?','Use alternating or rotating patterns.'],
 iq:['Find a rule that explains every given example.','Paper/pencil.','Test a candidate rule against all rows before using it.','Does your rule explain every example?','Use one-operation puzzles.'],
 geometry:['Decompose shapes into familiar pieces.','Tangrams/grid paper.','Split/build the figure from rectangles, triangles or unit squares.','What simpler shapes are inside?','Use two-piece shapes.'],
 parity:['Use odd/even as a constraint.','Counters paired into twos.','Pair counters and discover leftover/no-leftover rules.','Will there be a leftover?','Use numbers under 10.'],
 queue:['Translate front/back positions without double-counting.','Counters in a row.','Build people before and after; include the named person once.','Who is counted in both directions?','Use 2 before and 3 after.'],
 backwards:['Undo operations in reverse order.','Operation cards/arrows.','Start at the result; reverse the last operation first.','What happened last, and what undoes it?','Use two operations only.'],
 pigeonhole:['More objects than categories force a repeat.','Counters and cups.','Put one in each cup first; inspect what the next counter must do.','If each box had at most one, how many fit?','Use 4 counters and 3 cups.'],
 speed:['Connect distance, speed and time.','Toy figure and distance strip.','Show equal time steps before formulas.','How far in one time unit?','Use whole-number speeds/times.'],
 observation:['Extract visual information before calculating.','Matchsticks/counters/chapter diagram.','Describe and mark what is counted or moved.','What do you notice before touching the numbers?','Use one small diagram.'],
 multricks:['Regroup factors or distribute to make friendly products.','Array tiles/factor cards.','Make 10, 100 or 1000 using factor structure.','Can we rearrange factors to make a friendly product?','Use ×5, ×10, ×25.'],
 excess:['Compare an excess scenario with a shortage scenario.','Counters and two scenario cards.','Add excess+shortage; divide by change per item.','How far apart are the two scenarios?','Use per-item difference 1 or 2.'],
 catchup:['Use relative speed for chasing.','Two figures on a strip.','Show head start; gap closes by speed difference each minute.','How much gap disappears each minute?','Use a 10 m head start.'],
 meeting:['Use combined speed for objects moving toward each other.','Two figures on a strip.','Move both each minute; gap shrinks by sum of speeds.','How much distance disappears each minute?','Use speeds 2 and 3.'],
 journey:['Draw the route before calculating.','Long paper strip and counters.','Mark start, direction, stops and meeting points.','What is moving, which direction, what gap remains?','Use one traveler first.'],
 digits:['Apply digit/place-value/multiple restrictions systematically.','Digit cards/place-value mat.','List candidates and apply the strongest restriction first.','Which restriction shrinks the choices most?','Use two-digit numbers.'],
 cryptarithm:['Use column arithmetic and carries as constraints on digits.','Place-value columns/digit cards.','Start in ones; record carry possibilities; eliminate conflicts.','What must be true in this column?','Use 2 columns and 2–3 letters.'],
 perimeter:['Track the outside boundary only.','Square tiles/grid paper.','Trace exposed edges; ignore shared internal edges.','Is this edge outside or hidden inside?','Use two joined unit squares.'],
 numberpuzzle:['Translate a puzzle diagram into local arithmetic rules.','Counters/node diagram.','Write the equation represented by one small part first.','What equation does this part represent?','Use a 3-node sum puzzle.'],
 cubes:['Count hidden cubes by layers/stacks.','Unit cubes.','Rebuild when possible; count by layer or column.','What cubes must exist even if hidden?','Use a 2×2 base.'],
 shortest:['Count shortest paths recursively.','Grid paper.','Label start 1; each point gets sum of ways arriving from allowed previous points.','How many ways can arrive here?','Use a 2×2 grid.'],
 remainder:['Use divisor × quotient + remainder and remainder cycles.','Counters in equal groups.','Build full groups and leave leftovers visible.','How many full groups, what is left?','Use divisors 2–5.'],
 pagenumber:['Count printed digits in 1-digit/2-digit/3-digit blocks.','Number cards.','Split by digit length; pages × digits per page.','How many pages are in this digit block?','Count pages 1–20.'],
 newops:['Replace a new symbol with its definition before calculating.','Written rule card.','Substitute values into the definition exactly.','What does this symbol mean here?','Use one simple custom rule.'],
 onesdigit:['Find repeating cycles in the last digit.','Digit cards.','Compute only ones digits until the cycle repeats.','When does the last-digit pattern repeat?','Use powers of 2 or 5.'],
 arithmeticseq:['Use the constant difference in an arithmetic sequence.','Number cards.','Mark equal jumps before using a direct term rule.','What stays constant between terms?','Use 3,6,9,12…'],
 prime:['Test factor pairs to identify primes.','Counters as rectangular arrays.','Try arrays; prime means only 1×n and n×1.','Can both sides be greater than 1?','Use numbers under 30.'],
 divisibility:['Use divisibility tests to filter candidates.','Digit cards/rule card.','Apply easiest test first, then digit-sum tests.','Which test rules out most choices?','Start with 2,5,10.'],
 equations:['Translate to one unknown and undo operations.','Balance model.','Do the same inverse move to both sides.','What operation is attached to x?','Use x+5=12.'],
 average:['See average as equal sharing; total = average × count.','Counters in cups.','Redistribute equally, then connect to total÷count.','If shared equally, how many each?','Use 3 small groups.'],
 area:['Decompose/rearrange figures into familiar areas.','Grid paper/tiles.','Split into rectangles/triangles and add/subtract areas.','What simple shapes can we cut this into?','Use rectangles on a grid.'],
 fraction:['Create equal-sized fractional units before operating.','Fraction strips.','Build equivalent fractions before comparing/adding.','Are the pieces the same size yet?','Use halves/fourths.'],
 ratio:['Build ratio as equal batches and scale every part together.','Two colors of counters.','Build one ratio batch; repeat identical batches.','What does one complete ratio batch look like?','Use 2:1 or 3:1.'],
 percentage:['Connect percent to “out of 100”.','100-square/percent bar.','Show the percent on 100, then scale to the quantity.','What does this mean out of 100?','Use 10%,25%,50%.'],
 angles:['Use fixed angle totals: line 180°, point 360°, triangle 180°.','Paper angles/protractor.','Mark the fixed total first; fill one missing angle at a time.','What fixed total do these angles make?','Start with one straight-line angle.']
};
function os(){try{return JSON.parse(localStorage.getItem(OLY_KEY)||'{}')}catch(e){return {}}}let OD=os();if(!OD.progress)OD.progress={};function saveO(){localStorage.setItem(OLY_KEY,JSON.stringify(OD))}function prog(id){return OD.progress[id]||(OD.progress[id]={level:1,attempts:0,streak:0,mastered:false})}function rr(a,b){return Math.floor(Math.random()*(b-a+1))+a}function pk(a){return a[rr(0,a.length-1)]}function qq(text,answer,hint=''){return{text,answer,hint}}
function gen(ch,l){let t=ch.type;l=Math.max(1,Math.min(4,l||1));
 if(t==='time'){let h=rr(1,11),m=pk([0,15,30,45]),d=pk(l<3?[15,30,45,60]:[25,35,50,75,90]),z=h*60+m+d;return qq(`${h}:${String(m).padStart(2,'0')} + ${d} minutes`,`${Math.floor(z/60)%12||12}:${String(z%60).padStart(2,'0')}`)}
 if(t==='intervals'){let n=rr(3,l<3?8:20),d=pk([2,3,5,10]);return qq(`${n} equal intervals, each ${d} m. Total length?`,`${n*d} m`,'Count intervals, not posts.')}
 if(t==='fourops'){let a=rr(20,300),b=pk([9,19,49,99]);return qq(`${a} + ${b}`,a+b,`Try +${b+1}, then compensate 1.`)}
 if(t==='replace'){let x=rr(2,8),v=rr(2,9);return qq(`2 stars = 1 square. ${x} squares = ${2*x*v}. What is 1 star?`,v)}
 if(t==='age'){let d=rr(2,8),y=rr(6,12),k=rr(2,5);return qq(`Maya is ${y}; cousin is ${d} years older. How old is cousin when Maya is ${y+k}?`,y+d+k,'Difference stays fixed.')}
 if(t==='division'){let d=rr(2,9),q=rr(2,10);return qq(`${d*q} ÷ ${d}`,q)}
 if(t==='chicken'||t==='assuming'){let n=rr(5,12),r=rr(1,n-1),legs=2*n+2*r;return qq(`${n} chickens/rabbits have ${legs} legs. How many rabbits?`,r,'Assume all chickens.')}
 if(t==='pattern'){let a=rr(1,8),d=rr(2,6);return qq(`${a}, ${a+d}, ${a+2*d}, ${a+3*d}, ?`,a+4*d)}
 if(t==='counting'){let n=rr(3,l<3?6:10);return qq(`${n} people each shake hands once with every other person. Handshakes?`,n*(n-1)/2,'List systematically.')}
 if(t==='logic')return qq('Asha is not red. Ben is blue. Chen is not green. Each uses red/blue/green once. Asha?','green','Cross out impossible choices.')
 if(t==='listing'){let a=rr(2,4),b=rr(2,5);return qq(`${a} shirts and ${b} trousers. Different outfits?`,a*b)}
 if(t==='model'){let tot=rr(30,90),d=pk([4,6,8,10]);if((tot-d)%2)tot++;return qq(`Two numbers total ${tot}; one is ${d} more. Find both.`,`${(tot-d)/2} and ${(tot+d)/2}`)}
 if(t==='series'||t==='gauss'){let n=pk([10,20,30,50]);return qq(`1 + 2 + ... + ${n}`,n*(n+1)/2,'Pair first and last.')}
 if(t==='next'||t==='iq'||t==='observation')return qq('Use the next unsolved example on the chapter pages. Ask Maya to state the rule or three observations first.','Use the source solution.','Do not reveal the method first.')
 if(t==='geometry'){let a=rr(2,8),b=rr(2,8);return qq(`Rectangle ${a} squares by ${b} squares: unit squares?`,a*b)}
 if(t==='parity'){let a=rr(10,50),b=rr(10,50);return qq(`Without full calculation: ${a}+${b} odd or even?`,(a+b)%2?'odd':'even')}
 if(t==='queue'){let a=rr(2,12),b=rr(2,12);return qq(`${a} people in front of Maya, ${b} behind. Total queue?`,a+b+1)}
 if(t==='backwards'){let x=rr(2,12),a=rr(2,8),m=rr(2,4),z=(x+a)*m;return qq(`A number +${a}, then ×${m}, gives ${z}. Starting number?`,x)}
 if(t==='pigeonhole'){let b=rr(2,6),n=b*rr(2,4)+1;return qq(`${n} objects into ${b} boxes. Least number guaranteed in some box?`,Math.ceil(n/b))}
 if(t==='speed'){let s=rr(3,12),h=rr(2,8);return qq(`${s} km/h for ${h} h. Distance?`,`${s*h} km`)}
 if(t==='multricks'){let a=pk([12,16,24,32,48]),b=pk([25,125]);return qq(`${a} × ${b}`,a*b,'Regroup to make 100 or 1000.')}
 if(t==='excess'){let n=rr(5,12),a=rr(2,5),b=a+rr(1,3),extra=rr(1,5),tot=n*a+extra,short=n*b-tot;return qq(`Giving ${a} each leaves ${extra}; giving ${b} each is ${short} short. People?`,n)}
 if(t==='catchup'){let s=rr(2,6),f=s+rr(1,4),h=rr(2,8)*(f-s);return qq(`Head start ${h} m; speeds ${s} and ${f} m/min. Catch-up time?`,`${h/(f-s)} min`)}
 if(t==='meeting'||t==='journey'){let a=rr(2,7),b=rr(2,7),h=rr(2,8),d=(a+b)*h;return qq(`Two walkers ${d} m apart move toward each other at ${a}, ${b} m/min. Meet after?`,`${h} min`)}
 if(t==='digits'){let d=pk([2,5,10]);return qq(`How many 2-digit multiples of ${d}?`,Math.floor(99/d)-Math.floor(9/d))}
 if(t==='cryptarithm')return qq('A + A = B; A and B are different digits. Give one possible pair.','1,2 or 2,4 or 3,6 or 4,8')
 if(t==='perimeter'){let a=rr(2,10),b=rr(2,10);return qq(`Rectangle ${a} cm by ${b} cm: perimeter?`,`${2*(a+b)} cm`)}
 if(t==='numberpuzzle'){let a=rr(1,9),b=rr(1,9);return qq(`Top node = sum of two lower nodes ${a} and ${b}. Top?`,a+b)}
 if(t==='cubes'){let a=rr(2,4),b=rr(2,4),c=rr(2,4);return qq(`${a}×${b}×${c} block of unit cubes: how many?`,a*b*c)}
 if(t==='shortest'){let a=rr(1,3),b=rr(1,3),fact=n=>{let z=1;for(let i=2;i<=n;i++)z*=i;return z};return qq(`Shortest grid path needs ${a} right and ${b} down moves. How many?`,fact(a+b)/(fact(a)*fact(b)))}
 if(t==='remainder'){let d=rr(3,9),q=rr(2,12),r=rr(1,d-1);return qq(`${d*q+r} ÷ ${d}: quotient and remainder?`,`${q} remainder ${r}`)}
 if(t==='pagenumber'){let n=pk([15,20,25,30,40,50]);return qq(`Digits used numbering pages 1–${n}?`,9+(n-9)*2)}
 if(t==='newops'){let k=rr(2,5),a=rr(1,9),b=rr(1,9);return qq(`Define a ★ b = ${k}a+b. Find ${a} ★ ${b}.`,k*a+b)}
 if(t==='onesdigit'){let b=pk([2,3,4,7,8,9]),e=rr(5,20),z=1;for(let i=0;i<e;i++)z=z*b%10;return qq(`Ones digit of ${b}^${e}?`,z)}
 if(t==='arithmeticseq'){let a=rr(1,10),d=rr(2,8),n=rr(5,12);return qq(`Starts ${a}, common difference ${d}. Term ${n}?`,a+(n-1)*d)}
 if(t==='prime'){let n=pk([11,13,17,19,23,29,31,37,41,43]);return qq(`Is ${n} prime?`,'yes')}
 if(t==='divisibility'){let n=rr(100,999),d=pk([2,3,5,9,10]);return qq(`Is ${n} divisible by ${d}?`,n%d===0?'yes':'no')}
 if(t==='equations'){let x=rr(2,20),a=rr(2,8),b=rr(1,12),c=a*x+b;return qq(`${a}x + ${b} = ${c}. x?`,x)}
 if(t==='average'){let n=pk([3,4,5]),a=rr(5,20);return qq(`${n} numbers average ${a}. Total?`,n*a)}
 if(t==='area'){let a=rr(2,12),b=rr(2,10);return qq(`Area of ${a}×${b} rectangle?`,a*b)}
 if(t==='fraction'){let d=pk([4,6,8,10,12]),a=rr(1,d-1),b=rr(1,d-a);return qq(`${a}/${d} + ${b}/${d}`,`${a+b}/${d}`)}
 if(t==='ratio'){let a=rr(1,5),b=rr(1,5),k=rr(2,8);return qq(`Red:blue=${a}:${b}. Red=${a*k}. Blue?`,b*k)}
 if(t==='percentage'){let p=pk([10,20,25,50,75]),n=pk([40,60,80,100,120,200]);return qq(`${p}% of ${n}`,p*n/100)}
 if(t==='angles'){let a=rr(20,70),b=rr(20,70);if(a+b>=170)b=30;return qq(`Triangle angles ${a}°, ${b}°, ?.`,`${180-a-b}°`)}
 return qq('Use the next unsolved problem on the chapter pages.','Use source solution.')}
function pdfUrl(c){let b=OLY_BOOKS[c.book];return `/api/lesson-pdf?id=${encodeURIComponent(b.id)}&start=${c.start+b.offset}&end=${c.end+b.offset}`}function pages(c){let b=OLY_BOOKS[c.book];return `Book pp. ${c.start}–${c.end} · PDF pp. ${c.start+b.offset}–${c.end+b.offset}`}
let OC=null,OQ=null;
function renderOlympiadHome(){homeBtn.onclick=renderProfiles;screen.innerHTML=`<div class="crumbs"><button class="text-link" id="ob">Math profiles</button><span>›</span><span>Olympiad Math</span></div><div class="eyebrow">TERRY CHEW</div><h2>Olympiad Math</h2><p class="lead">Choose a level. Each chapter is a parent intervention: teach one strategy, try one problem, report what happened, then move up, stay, or make it more concrete.</p><div class="unit-grid">${Object.entries(OLY_BOOKS).map(([k,b])=>{let cs=OLY_CHAPTERS.filter(c=>c.book===k),m=cs.filter(c=>prog(c.id).mastered).length;return `<button class="unit-tile" data-ob="${k}"><strong>${b.title}</strong><span>${b.grade} · ${b.age}</span><span class="unit-progress">${m}/${cs.length} mastered</span></button>`}).join('')}</div>`;document.getElementById('ob').onclick=renderProfiles;screen.querySelectorAll('[data-ob]').forEach(x=>x.onclick=()=>renderOlympiadBook(x.dataset.ob))}
function renderOlympiadBook(k){let b=OLY_BOOKS[k],cs=OLY_CHAPTERS.filter(c=>c.book===k);screen.innerHTML=`<div class="crumbs"><button class="text-link" id="oh">Olympiad Math</button><span>›</span><span>${b.title}</span></div><h2>${b.title}</h2><p class="lead">${b.grade} · ${b.age}. Work by strategy, not speed.</p><div class="lesson-list">${cs.map(c=>{let p=prog(c.id);return `<button class="lesson-tile" data-oc="${c.id}"><div><strong>${c.n}. ${c.title}</strong><span>pp. ${c.start}–${c.end}</span></div><span class="status ${p.mastered?'mastered':''}">${p.mastered?'Mastered':p.attempts?`Level ${p.level}`:'Not started'}</span></button>`}).join('')}</div>`;document.getElementById('oh').onclick=renderOlympiadHome;screen.querySelectorAll('[data-oc]').forEach(x=>x.onclick=()=>renderOlympiadChapter(x.dataset.oc))}
function renderOlympiadChapter(id){let c=OLY_CHAPTERS.find(x=>x.id===id),s=STR[c.type]||STR.observation,p=prog(id);OC=c;screen.innerHTML=`<div class="eyebrow">${OLY_BOOKS[c.book].title} · Chapter ${c.n}</div><h2>${c.title}</h2><div class="card soft page-card"><div class="label">BOOK PAGES</div><strong>${pages(c)}</strong><div class="page-actions"><a class="page-link primary" href="${pdfUrl(c)}" target="_blank">Open chapter pages</a></div></div><div class="card"><div class="label">TEACH ONLY THIS</div><p class="script">${s[0]}</p></div><div class="card"><div class="label">PUT ON THE TABLE</div><p class="script">${s[1]}</p></div><div class="card"><div class="label">DO</div><p class="script">${s[2]}</p></div><div class="card soft"><div class="label">SAY</div><p class="script">${s[3]}</p></div><div class="actions"><button id="oq" class="primary">Give me a question</button><button id="olow" class="secondary">She is not confident yet</button></div>`;document.getElementById('oq').onclick=()=>renderOlympiadQuestion(c,p.level);document.getElementById('olow').onclick=()=>renderOlympiadIntervention('notconf')}
function renderOlympiadQuestion(c,l){OQ=gen(c,l);screen.innerHTML=`<div class="eyebrow">${c.title} · Level ${l}</div><div class="card soft page-card"><div class="label">SOURCE</div><strong>${pages(c)}</strong><div class="page-actions"><a class="page-link secondary" href="${pdfUrl(c)}" target="_blank">Open chapter pages</a></div></div><div class="question-box"><div class="label">ASK MAYA</div><div class="q">${OQ.text}</div><div class="hint">${OQ.hint||''}</div></div><div class="card soft"><div class="label">PARENT ANSWER</div><p class="script"><strong>${OQ.answer}</strong></p></div><p class="focus">What happened?</p><div class="outcomes"><button data-oo="confident"><strong>Right + confident</strong></button><button data-oo="help"><strong>Right, but needed help</strong></button><button data-oo="idea"><strong>Answer right, strategy shaky</strong></button><button data-oo="lost"><strong>Lost track midway</strong></button><button data-oo="different"><strong>Different valid method</strong></button><button data-oo="wrong"><strong>Wrong / unsure</strong></button></div>`;screen.querySelectorAll('[data-oo]').forEach(x=>x.onclick=()=>renderOlympiadIntervention(x.dataset.oo))}
function up(out){let p=prog(OC.id),e='stay';p.attempts++;if(out==='confident'){p.streak++;if(p.streak>=2){if(p.level<4){p.level++;p.streak=0;e='levelup'}else{p.mastered=true;p.streak=0;e='mastered'}}}else p.streak=0;saveO();return e}function nxt(c){let a=OLY_CHAPTERS.filter(x=>x.book===c.book);return a[a.findIndex(x=>x.id===c.id)+1]||null}
function renderOlympiadIntervention(out){let c=OC,s=STR[c.type]||STR.observation,e=up(out),p=prog(c.id),n=nxt(c),title='',body='',tone='';if(out==='confident'){if(e==='mastered'){title='Mastered for now';body='Two confident answers at Level 4. Stop drilling this strategy and move on.';tone='good'}else if(e==='levelup'){title=`Move to Level ${p.level}`;body='Two confident answers were enough. The next problem expects a little more independence.';tone='good'}else{title='One confirming question';body='Ask one more at this level. Two confident answers move her up.'}}if(out==='help'){title='Stay here';body='Use another problem with the same structure. Keep the visual/model and remove only one prompt.'}if(out==='idea'){title='Make the strategy visible';body='Keep the mathematics, but externalize the structure with the suggested materials.';tone='warn'}if(out==='lost'){title='Reduce memory load';body='Write/build every intermediate state. Maya should make one move at a time.';tone='warn'}if(out==='different'){title='Keep the valid method';body='Have Maya show why her method works. If valid, accept it, then compare the chapter method as another tool.'}if(out==='wrong'){title='Find the first break';body='Check: represent the situation → name the strategy → make first move → keep result. The first “no” is the intervention point.';tone='warn'}if(out==='notconf'){title='Move down in representation';body=s[4];tone='warn'}let pr=p.mastered?`<div class="mastery-box"><strong>Done for today.</strong><span>Mastered for now.</span></div>`:`<div class="mastery-line"><strong>Level ${p.level}/4</strong><span>${p.streak}/2 confident answers</span></div>`;screen.innerHTML=`<div class="eyebrow">NEXT PARENT MOVE</div><h2>${title}</h2>${pr}<div class="result ${tone}"><div class="route-title">${title}</div><p class="route-copy">${body}</p></div><div class="card soft page-card"><div class="label">SOURCE CHAPTER</div><strong>${pages(c)}</strong><div class="page-actions"><a class="page-link secondary" href="${pdfUrl(c)}" target="_blank">Open chapter pages</a></div></div><div class="toolbar">${p.mastered&&n?`<button id="onext" class="primary">Next chapter: ${n.title}</button>`:`<button id="oagain" class="primary">${e==='levelup'?`Try Level ${p.level}`:'Another question'}</button>`}<button id="oteach" class="secondary">Teaching steps</button><button id="obook" class="quiet">Back to ${OLY_BOOKS[c.book].title}</button></div>`;let a=document.getElementById('oagain');if(a)a.onclick=()=>renderOlympiadQuestion(c,p.level);let nn=document.getElementById('onext');if(nn)nn.onclick=()=>renderOlympiadChapter(n.id);document.getElementById('oteach').onclick=()=>renderOlympiadChapter(c.id);document.getElementById('obook').onclick=()=>renderOlympiadBook(c.book)}
window.renderOlympiadHome=renderOlympiadHome;