// Maya · Speed Math for Kids (Bill Handley) parent-coach profile
const SM_KEY='mayaSpeedMath.v1';
const SM_BOOK={id:'1MW9NEEnhGxQ-y5JHR6vr6pyOA_Z3_doY',title:'Speed Math for Kids',offset:8};
const SM_RAW=[
[1,'Multiplication: Getting Started',4,'ref10'],[2,'Using a Reference Number',13,'reference'],[3,'Numbers Above the Reference Number',21,'above'],[4,'Multiplying Above & Below the Reference Number',29,'mixedref'],[5,'Checking Your Answers',34,'check'],[6,'Multiplication Using Any Reference Number',43,'anyref'],[7,'Multiplying Lower Numbers',59,'lower'],[8,'Multiplication by 11',69,'times11'],[9,'Multiplying Decimals',77,'decimals'],[10,'Multiplication Using Two Reference Numbers',87,'tworef'],[11,'Addition',106,'addition'],[12,'Subtraction',116,'subtraction'],[13,'Simple Division',130,'simplediv'],[14,'Long Division by Factors',141,'factorsdiv'],[15,'Standard Long Division Made Easy',149,'longdiv'],[16,'Direct Long Division',157,'directdiv'],[17,'Checking Answers (Division)',166,'checkdiv'],[18,'Fractions Made Easy',173,'fractions'],[19,'Direct Multiplication',185,'directmult'],[20,'Putting It All into Practice',195,'mixed']];
const SM_CHAPTERS=SM_RAW.map((r,i)=>({n:r[0],title:r[1],start:r[2],end:i<SM_RAW.length-1?SM_RAW[i+1][2]-1:198,type:r[3],id:`sm-${r[0]}`}));
const SM_APPENDICES=[['A','Using the Methods in the Classroom',203],['B','Working Through a Problem',207],['C','Learn the 13, 14 and 15 Times Tables',209],['D','Tests for Divisibility',211],['E','Keeping Count',215],['F','Plus and Minus Numbers',217],['G','Percentages',219],['H','Hints for Learning',223],['I','Estimating',225],['J','Squaring Numbers Ending in 5',227],['K','Practice Sheets',231]];
const SM_STR={
ref10:['Use 10 or 100 as a friendly anchor for multiplication.','Number cards or place-value blocks.','Write how far each factor is from 10 (or 100), subtract crossways, then multiply the small differences.','“How far is each number from 10? What happens if we use that distance?”','Start with 8×6, 9×7, then near-100 examples.'],
reference:['Make the reference number explicit before calculating.','Paper with a large 10 or 100 written at the left.','Choose the nearby power of ten, record each difference from it, then use the book’s crossways step and product-of-differences step.','“What friendly reference are both numbers close to?”','Stay with both numbers below 10 until the structure is secure.'],
above:['Use the same reference method when both numbers are above the anchor.','Number cards around 10.','Record + differences above 10; cross-add for the first part and multiply the differences for the last part.','“How much above 10 is each number?”','Use 11×12 or 12×13 before larger examples.'],
mixedref:['Handle one factor above and one below the reference number.','Number line centered at 10 or 100.','Mark one positive and one negative difference. Cross-calculate carefully, then combine the signed small-product part.','“Which number is above the reference? Which is below?”','Use numbers only 1–3 away from 10.'],
check:['Check calculations independently using the book’s casting-out-nines method.','Digit cards or paper.','Reduce each factor and the answer by digit sums; compare the check result.','“Can we test the answer without doing the whole multiplication again?”','Start with one-digit products whose digit sums are obvious.'],
anyref:['Choose a useful reference such as 20 or 50 by relating it to 10 or 100.','Reference cards: 10, 20, 50, 100.','Identify how the chosen reference relates to 10 or 100, then scale the first part accordingly.','“Which reference is closest, and how is it related to 10 or 100?”','Use 20 first: double, then ×10.'],
lower:['Adapt the method for smaller numbers and easy reference points.','Number cards and a 10-reference card.','Use the nearest easy reference and keep the adjustment visible rather than relying on memorized tables alone.','“What nearby number makes this easier?”','Keep factors under 12.'],
times11:['Exploit the structure of multiplying by 11.','Two-digit number cards.','For a two-digit number ab, keep the outer digits and place their sum in the middle, carrying when needed.','“What do the two digits add to?”','Use examples whose digit sum is below 10 first.'],
decimals:['Use the same multiplication method on whole-number digits, then restore decimal place value.','Place-value chart.','Temporarily ignore decimal points, calculate, then reason about the size/place value of the answer.','“About how big should the answer be?”','Use one decimal place in each factor.'],
tworef:['Use different reference numbers when the factors are not near the same anchor.','Two reference cards.','Choose related references; account for the multiplier connecting them before combining the parts.','“What two friendly numbers are these close to, and how are those references related?”','Use 10 and 20 before more complicated pairs.'],
addition:['Add near-friendly numbers by over-adding and compensating.','Number line or hundred chart.','For +9 use +10−1; for +95 use +100−5. Keep the compensation visible.','“What friendly amount could we add instead? What must we give back?”','Start with +9 and +8.'],
subtraction:['Subtract near-friendly numbers by over-subtracting and giving back.','Number line or hundred chart.','For −9 use −10+1; for −98 use −100+2.','“If we subtract a friendly amount, how much did we take too much?”','Start with −9 and −8.'],
simplediv:['Treat simple division as a mental inverse of multiplication.','Counters and fact-family cards.','Ask what number times the divisor gives the dividend; use easy factors and remainders as needed.','“What multiplication fact would undo this division?”','Use exact divisions from known tables.'],
factorsdiv:['Break a divisor into easy factors and divide in stages.','Factor cards.','Factor the divisor, then divide by one factor at a time.','“Can we split this divisor into easier factors?”','Use divisors such as 12=3×4.'],
longdiv:['Make long division predictable by estimating each quotient digit and checking by multiplication.','Place-value chart.','Work one place at a time: estimate, multiply back, subtract, bring down.','“What is a sensible quotient digit here?”','Use a one-digit divisor first.'],
directdiv:['Compress long division once the standard structure is secure.','Paper and place-value chart.','Keep the same place-value logic but record fewer intermediate lines.','“Can you hold this step mentally without losing the remainder?”','Only use after standard long division is reliable.'],
checkdiv:['Check division by reversing it: quotient × divisor + remainder = dividend.','Fact-family card.','Rebuild the dividend from quotient, divisor and remainder.','“If this division is right, what multiplication should recreate the starting number?”','Start with exact division, then add small remainders.'],
fractions:['Treat fraction questions through common units, multiplication and division relationships.','Fraction strips.','Make the pieces comparable first; then use the book’s arithmetic shortcut only after the fraction meaning is clear.','“What size pieces are we counting?”','Use halves, thirds and quarters.'],
directmult:['Multiply directly by decomposing place values and combining partial products mentally.','Place-value cards.','Break one factor into tens/ones, form partial products, and combine while keeping place value visible.','“Which part can you multiply first without losing track?”','Use two-digit × one-digit first.'],
mixed:['Choose the easiest valid method instead of forcing one trick.','No special material at first; add one only if needed.','Pause before calculating and identify the structure: reference number, compensation, factorization, direct method, or standard algorithm.','“What makes these numbers special? Which method is easiest here?”','Compare two valid methods on the same problem.']};
function smLoad(){try{return JSON.parse(localStorage.getItem(SM_KEY)||'{}')}catch(e){return {}}}let SMD=smLoad();if(!SMD.progress)SMD.progress={};
function smSave(){localStorage.setItem(SM_KEY,JSON.stringify(SMD))}function smProg(id){return SMD.progress[id]||(SMD.progress[id]={level:1,streak:0,attempts:0,mastered:false})}
function smPdf(c){return `/api/lesson-pdf?id=${encodeURIComponent(SM_BOOK.id)}&start=${c.start+SM_BOOK.offset}&end=${c.end+SM_BOOK.offset}`}
function smPages(c){return `Book pp. ${c.start}–${c.end} · PDF pp. ${c.start+8}–${c.end+8}`}
function smR(a,b){return Math.floor(Math.random()*(b-a+1))+a}function smPick(a){return a[smR(0,a.length-1)]}
function smQ(text,answer,hint=''){return {text,answer,hint}}
function smGen(c,l){l=Math.max(1,Math.min(4,l||1));switch(c.type){
case'ref10':case'reference':{let a=smPick(l<3?[6,7,8,9]:[92,93,94,96,97,98]),ref=a<20?10:100,b=ref-smR(1,l<3?4:8);return smQ(`${a} × ${b}`,a*b,`Use reference ${ref}.`)}
case'above':{let a=smR(11,l<3?15:25),b=smR(11,l<3?15:25);return smQ(`${a} × ${b}`,a*b,'Use 10 or 20 as the reference.')}case'mixedref':{let a=smR(11,15),b=smR(6,9);return smQ(`${a} × ${b}`,a*b,'One is above 10 and one below.')}case'times11':{let n=smR(12,l<3?69:98);return smQ(`${n} × 11`,n*11,'Keep outer digits; add the digits for the middle, carrying if needed.')}case'addition':{let a=smR(20,400),b=smPick([8,9,18,19,48,49,95,98,99]);return smQ(`${a} + ${b}`,a+b,'Add a friendly number, then compensate.')}case'subtraction':{let b=smPick([8,9,18,19,48,49,95,98,99]),a=smR(b+20,b+400);return smQ(`${a} − ${b}`,a-b,'Subtract a friendly number, then give back.')}case'simplediv':{let d=smR(2,10),q=smR(2,12);return smQ(`${d*q} ÷ ${d}`,q,'Use the related multiplication fact.')}case'factorsdiv':{let d=smPick([12,15,18,20,24]),q=smR(2,8);return smQ(`${d*q} ÷ ${d}`,q,'Factor the divisor and divide in stages.')}case'checkdiv':{let d=smR(2,9),q=smR(2,15),r=smR(0,d-1),n=d*q+r;return smQ(`${n} ÷ ${d}`,r?`${q} remainder ${r}`:q,'Check with quotient × divisor + remainder.')}case'decimals':{let a=smR(12,49)/10,b=smR(12,39)/10;return smQ(`${a.toFixed(1)} × ${b.toFixed(1)}`,(a*b).toFixed(2),'Estimate size before replacing decimal point.')}case'fractions':{let d=smPick([2,3,4,5,6,8]),n=smR(1,d-1);return smQ(`What fraction completes ${n}/${d} to make 1?`,`${d-n}/${d}`)}case'directmult':{let a=smR(12,99),b=smR(2,9);return smQ(`${a} × ${b}`,a*b,'Split tens and ones if helpful.')}default:{let a=smR(12,99),b=smR(2,15);return smQ(`${a} × ${b}`,a*b,'Choose the easiest valid method.')}}}
let SMC=null,SMQ=null;
function renderSpeedMathHome(){homeBtn.onclick=renderProfiles;screen.innerHTML=`<div class="crumbs"><button class="text-link" id="smb">Math profiles</button><span>›</span><span>Speed Math</span></div><div class="eyebrow">MAYA · BILL HANDLEY</div><h2>Speed Math for Kids</h2><p class="lead">A mental-calculation profile. We use the book’s methods as optional tools, not as speed pressure. The author describes it as a book for younger people to play and experiment with rather than a serious textbook.</p><div class="lesson-list">${SM_CHAPTERS.map(c=>{let p=smProg(c.id);return `<button class="lesson-tile" data-sm="${c.id}"><div><strong>${c.n}. ${c.title}</strong><span>${smPages(c)}</span></div><span class="status ${p.mastered?'mastered':''}">${p.mastered?'Secure':p.attempts?`Level ${p.level}`:'Not started'}</span></button>`}).join('')}</div><div class="card"><div class="label">BOOK APPENDICES</div>${SM_APPENDICES.map(a=>`<div class="mini" style="padding:4px 0"><strong>${a[0]}.</strong> ${a[1]} · p. ${a[2]}</div>`).join('')}</div>`;document.getElementById('smb').onclick=renderProfiles;screen.querySelectorAll('[data-sm]').forEach(x=>x.onclick=()=>renderSMChapter(x.dataset.sm))}
function renderSMChapter(id){let c=SM_CHAPTERS.find(x=>x.id===id),s=SM_STR[c.type],p=smProg(id);SMC=c;screen.innerHTML=`<div class="eyebrow">MAYA · CHAPTER ${c.n}</div><h2>${c.title}</h2><div class="card soft page-card"><div class="label">SOURCE PAGES</div><strong>${smPages(c)}</strong><div class="page-actions"><a class="page-link primary" href="${smPdf(c)}" target="_blank">Open chapter pages</a></div></div><div class="card"><div class="label">TEACH ONLY THIS</div><p class="script">${s[0]}</p></div><div class="card"><div class="label">PUT ON THE TABLE</div><p class="script">${s[1]}</p></div><div class="card"><div class="label">DO</div><p class="script">${s[2]}</p></div><div class="card soft"><div class="label">SAY</div><p class="script">${s[3]}</p></div><div class="actions"><button id="smq" class="primary">Give me a question</button><button id="smlow" class="secondary">She is not confident yet</button></div>`;document.getElementById('smq').onclick=()=>renderSMQuestion(c,p.level);document.getElementById('smlow').onclick=()=>renderSMIntervention('notconf')}
function renderSMQuestion(c,l){SMQ=smGen(c,l);screen.innerHTML=`<div class="eyebrow">${c.title} · Level ${l}</div><div class="question-box"><div class="label">ASK MAYA</div><div class="q">${SMQ.text}</div><div class="hint">${SMQ.hint}</div></div><div class="card soft"><div class="label">PARENT ANSWER</div><p class="script"><strong>${SMQ.answer}</strong></p></div><p class="focus">What happened?</p><div class="outcomes"><button data-smo="confident"><strong>Right + confident</strong></button><button data-smo="help"><strong>Right, but needed help</strong></button><button data-smo="idea"><strong>Answer right, method shaky</strong></button><button data-smo="lost"><strong>Lost track midway</strong></button><button data-smo="different"><strong>Different valid method</strong></button><button data-smo="wrong"><strong>Wrong / unsure</strong></button></div>`;screen.querySelectorAll('[data-smo]').forEach(x=>x.onclick=()=>renderSMIntervention(x.dataset.smo))}
function smUp(out){let p=smProg(SMC.id),e='stay';p.attempts++;if(out==='confident'){p.streak++;if(p.streak>=2){if(p.level<4){p.level++;p.streak=0;e='levelup'}else{p.mastered=true;p.streak=0;e='mastered'}}}else p.streak=0;smSave();return e}
function renderSMIntervention(out){let c=SMC,s=SM_STR[c.type],e=smUp(out),p=smProg(c.id),title='',body='',tone='';if(out==='confident'){if(e==='mastered'){title='Secure for now';body='Two confident answers at Level 4. Stop drilling this method; use it later in mixed review.';tone='good'}else if(e==='levelup'){title=`Move to Level ${p.level}`;body='Two confident answers were enough. The next question uses less obvious numbers or less prompting.';tone='good'}else{title='One confirming question';body='One more confident answer at this level moves her up.'}}if(out==='help'){title='Stay here';body='Use another problem with the same structure and one fewer prompt.'}if(out==='idea'){title='Make the adjustment visible';body='Keep the same calculation, but show the reference number, difference, or compensation physically/on paper.';tone='warn'}if(out==='lost'){title='Reduce memory load';body='Leave each intermediate number visible. One move at a time; do not make the arithmetic artificially easier unless the concept itself is shaky.';tone='warn'}if(out==='different'){title='Keep the valid method';body='Accept Maya’s method if it works. Then compare the book method as another tool, not the required answer.'}if(out==='wrong'){title='Find the first break';body='Check: can she identify the friendly number/reference → state the adjustment → do the easy calculation → compensate correctly? Stop at the first “no”.';tone='warn'}if(out==='notconf'){title='Move down in representation';body=s[4];tone='warn'}screen.innerHTML=`<div class="eyebrow">NEXT PARENT MOVE</div><h2>${title}</h2><div class="mastery-line"><strong>Level ${p.level}/4</strong><span>${p.streak}/2 confident answers</span></div><div class="result ${tone}"><div class="route-title">${title}</div><p class="route-copy">${body}</p></div><div class="card soft page-card"><div class="label">SOURCE</div><strong>${smPages(c)}</strong><div class="page-actions"><a class="page-link secondary" href="${smPdf(c)}" target="_blank">Open chapter pages</a></div></div><div class="toolbar"><button id="smagain" class="primary">${e==='levelup'?`Try Level ${p.level}`:'Another question'}</button><button id="smteach" class="secondary">Teaching steps</button><button id="smhome" class="quiet">Back to Speed Math</button></div>`;document.getElementById('smagain').onclick=()=>renderSMQuestion(c,p.level);document.getElementById('smteach').onclick=()=>renderSMChapter(c.id);document.getElementById('smhome').onclick=renderSpeedMathHome}
window.renderSpeedMathHome=renderSpeedMathHome;
