// Maya · Speed Math for Kids — rebuilt from the complete Bill Handley book.
// Parent-facing: LEARN the method first, PRACTICE separately.
const SM_KEY='mayaSpeedMath.v2';
const SM_BOOK={id:'1MW9NEEnhGxQ-y5JHR6vr6pyOA_Z3_doY',title:'Speed Math for Kids',offset:8};

const SM_CHAPTERS=[
 {n:1,title:'Multiplication: Getting Started',start:4,end:12,id:'sm-1',type:'refbelow',learn:{idea:'Multiply numbers near 10 or 100 by measuring how far each number is below the friendly number.',steps:['Choose the friendly number: 10 for single-digit factors near 10, or 100 for two-digit factors near 100.','Find each shortfall. For 8 × 6, the shortfalls from 10 are 2 and 4.','Subtract crossways once: 8 − 4 or 6 − 2. Both give 4.','Multiply that crossways result by the reference number: 4 × 10 = 40.','Multiply the two shortfalls: 2 × 4 = 8.','Add: 40 + 8 = 48.'],example:{problem:'8 × 6',work:['10 is the reference.','8 is 2 below 10; 6 is 4 below 10.','Cross-subtract: 8 − 4 = 4.','4 × 10 = 40.','2 × 4 = 8.','40 + 8 = 48.'],answer:'48'},when:'Use when both factors sit fairly close below the same easy reference number.',watch:'The first part is not just “4”; it represents 4 tens when the reference is 10, or 4 hundreds when the reference is 100.'}},
 {n:2,title:'Using a Reference Number',start:13,end:20,id:'sm-2',type:'reference',learn:{idea:'Write the reference number explicitly so the method works even when the small product has two digits.',steps:['Write 10 or 100 to the left as the reference.','Mark how far each factor is below it.','Subtract crossways.','Multiply the crossways answer by the reference number to make the subtotal.','Multiply the shortfalls.','Add the small product to the subtotal.'],example:{problem:'6 × 7',work:['Reference 10.','6 is 4 below; 7 is 3 below.','Cross-subtract: 6 − 3 = 3.','3 × 10 = 30.','4 × 3 = 12.','30 + 12 = 42.'],answer:'42'},when:'Use whenever the Chapter 1 shortcut could become ambiguous—for example 6 × 7, where the small product is 12.',watch:'Do not simply write the small product after the first number. The reference-number multiplication is what keeps the place value correct.'}},
 {n:3,title:'Numbers Above the Reference Number',start:21,end:28,id:'sm-3',type:'above',learn:{idea:'The same structure works above 10 or 100; the differences are now positive and the crossways move is addition.',steps:['Choose 10 or 100.','Find how far each factor is above the reference.','Add crossways once.','Multiply that result by the reference number.','Multiply the two positive differences.','Add the two parts.'],example:{problem:'13 × 15',work:['Reference 10.','13 is 3 above; 15 is 5 above.','Cross-add: 13 + 5 = 18.','18 × 10 = 180.','3 × 5 = 15.','180 + 15 = 195.'],answer:'195'},when:'Use when both factors are above the same nearby reference.',watch:'Above means add crossways. Below means subtract crossways. The side products are positive when both differences have the same sign.'}},
 {n:4,title:'Multiplying Above & Below the Reference Number',start:29,end:33,id:'sm-4',type:'mixedref',learn:{idea:'When one factor is above and the other below the reference, the small product is negative, so it must be subtracted from the subtotal.',steps:['Choose a shared reference.','Mark one positive difference and one negative difference.','Cross-add/subtract to get the main part.','Multiply by the reference number.','Multiply the signed differences; one positive × one negative gives a negative result.','Subtract that amount from the subtotal.'],example:{problem:'97 × 125',work:['Reference 100.','97 is 3 below; 125 is 25 above.','Crossways: 125 − 3 = 122.','122 × 100 = 12,200.','(−3) × 25 = −75.','12,200 − 75 = 12,125.'],answer:'12,125'},when:'Use when both numbers are reasonably close to one reference but lie on opposite sides.',watch:'The sign matters. If one difference is above and one below, the final small product is subtracted.'}},
 {n:5,title:'Checking Your Answers',start:34,end:42,id:'sm-5',type:'check',learn:{idea:'Check arithmetic with digit sums (casting out nines) without redoing the original calculation.',steps:['Replace each input number with its digit sum, repeatedly reducing to one digit. You may cross out 9s or groups that total 9.','Perform the same operation on the substitute numbers.','Reduce that result to one digit.','Reduce the digits of your original answer the same way.','If the two check values differ, the original answer is definitely wrong. If they match, the answer passes the check.'],example:{problem:'12 × 14 = 168',work:['12 → 1+2 = 3.','14 → 1+4 = 5.','3 × 5 = 15 → 1+5 = 6.','168 → 1+6+8 = 15 → 6.','The check values match: 6 and 6.'],answer:'Passes the check'},when:'Use after multiplication, addition, subtraction or division as an error detector.',watch:'A matching digit-sum check does not prove an answer is correct; some wrong answers can also have the same remainder mod 9.'}},
 {n:6,title:'Multiplication Using Any Reference Number',start:43,end:58,id:'sm-6',type:'anyref',learn:{idea:'Use references such as 20 or 50 by expressing them through easy factors of 10 or 100.',steps:['Choose a reference close to the factors: 20, 50, 200, etc.','Find each factor’s difference from that reference.','Do the same crossways addition/subtraction as before.','Multiply the crossways result by the reference using easy factors: ×20 = ×2 then ×10; ×50 = ×100 then ÷2.','Multiply the two differences.','Add or subtract the side product according to the signs.'],example:{problem:'23 × 21',work:['Reference 20.','Differences are +3 and +1.','Cross-add: 23 + 1 = 24.','24 × 20 = 24 × 2 × 10 = 480.','3 × 1 = 3.','480 + 3 = 483.'],answer:'483'},when:'Use when 10 or 100 is not close enough but another reference is easy to multiply by.',watch:'The hard part is not the crossways step; it is multiplying by the chosen reference correctly. Teach the factor relationship first.'}},
 {n:7,title:'Multiplying Lower Numbers',start:59,end:68,id:'sm-7',type:'lower',learn:{idea:'For small factors, the book experiments with reference 5, but its genuinely useful shortcut here is multiplying by 5 as ×10 then half.',steps:['For ×5, multiply the number by 10.','Halve that result.','If halving an odd number of tens is awkward, split it into friendly parts first.','The book also demonstrates reference 5 for low-number multiplication, but explicitly notes that memorized basic facts are usually simpler.'],example:{problem:'23 × 5',work:['23 × 10 = 230.','Split 230 as 220 + 10.','Half of 220 is 110; half of 10 is 5.','110 + 5 = 115.'],answer:'115'},when:'Use the ×5 shortcut freely. Treat “reference 5” mainly as mathematical play, not a required algorithm.',watch:'Do not force the reference-5 method for facts such as 6 × 4. The author himself says it is not the easiest way to learn low tables.'}},
 {n:8,title:'Multiplication by 11',start:69,end:76,id:'sm-8',type:'times11',learn:{idea:'For two-digit numbers, place the sum of the two digits between them; for longer numbers, add neighboring digits.',steps:['Two-digit case: keep the outside digits.','Add the two digits and place the sum between them.','If the sum is 10 or more, write its ones digit in the middle and carry 1 to the left digit.','Longer-number case: put an imaginary 0 at the left and right edges, then add neighboring digits from right to left, carrying 1 when needed.'],example:{problem:'84 × 11',work:['Outer digits are 8 and 4.','8 + 4 = 12.','Put 2 in the middle and carry 1 to the 8.','8 + 1 = 9.','Result: 924.'],answer:'924'},when:'Use for multiplying any whole number by 11; begin with two-digit numbers before the general neighboring-digit rule.',watch:'The middle is the sum, not a concatenation. When the sum exceeds 9, carry before finalizing the left side.'}},
 {n:9,title:'Multiplying Decimals',start:77,end:86,id:'sm-9',type:'decimals',learn:{idea:'Do the multiplication as if the factors were whole numbers, then restore the decimal by counting total decimal places and checking magnitude by estimation.',steps:['Ignore decimal points temporarily and multiply the digit strings.','Count the total number of decimal places in both factors.','Place the decimal in the product so it has that many decimal places.','If necessary, insert leading zeros.','Estimate the size of the answer to catch a misplaced decimal.'],example:{problem:'9.6 × 9.7',work:['Ignore decimals: 96 × 97 = 9,312.','There are 2 decimal places total.','Place the decimal two digits from the right: 93.12.','Estimate 10 × 10 ≈ 100, so 93.12 is sensible.'],answer:'93.12'},when:'Use with any multiplication method once the whole-number product is reliable.',watch:'Casting out nines can check the digits but not the decimal-point position. Always estimate.'}},
 {n:10,title:'Multiplication Using Two Reference Numbers',start:87,end:105,id:'sm-10',type:'tworef',learn:{idea:'When the two factors are far apart, give each its own related reference number and scale one difference before the crossways step.',steps:['Choose a main easy reference (usually 10 or 100) for one factor.','Choose a second reference for the other factor that is a multiple or fraction of the main reference.','Find each factor’s signed difference from its own reference.','Scale the first factor’s difference by the multiplier connecting the references.','Use that scaled difference crossways with the second factor.','Multiply the crossways result by the main reference.','Multiply the original two differences and add/subtract according to sign.'],example:{problem:'8 × 37',work:['References: 10 and 40 = 10 × 4.','8 is 2 below 10; 37 is 3 below 40.','Scale the first shortfall: 2 × 4 = 8.','37 − 8 = 29.','29 × 10 = 290.','2 × 3 = 6.','290 + 6 = 296.'],answer:'296'},when:'Use only when the factors are not close to one common reference and the two chosen references have an easy relationship.',watch:'This is advanced. If the reference relationship itself takes more effort than ordinary multiplication, choose a simpler method.'}},
 {n:11,title:'Addition',start:106,end:115,id:'sm-11',type:'addition',learn:{idea:'Add mentally from left to right, and round awkward addends to friendly numbers then compensate.',steps:['For an awkward addend such as 90, 95, 9 or 8, replace it with a nearby easy amount.','Add the easy amount.','Compensate for the amount you over-added.','For multi-digit addition, work from the largest place toward the smallest so you keep a running total.','Break numbers into parts that make friendly sums when helpful.'],example:{problem:'46 + 90',work:['90 is 10 less than 100.','46 + 100 = 146.','146 − 10 = 136.'],answer:'136'},when:'Use compensation for near-10/100 addends and left-to-right chunking for general mental addition.',watch:'The adjustment must go in the opposite direction: if you added too much, subtract the extra.'}},
 {n:12,title:'Subtraction',start:116,end:129,id:'sm-12',type:'subtraction',learn:{idea:'Round the amount being subtracted to an easy number, subtract it, then give back the amount you took too much.',steps:['Round the subtrahend up to a friendly 10, 100, 1000, etc.','Subtract the friendly number.','Find how much extra you subtracted.','Add that amount back.','For numbers just above and below the same hundred/tens boundary, combine the two gaps instead of performing a full subtraction.'],example:{problem:'537 − 298',work:['298 is 2 less than 300.','537 − 300 = 237.','Give back 2.','237 + 2 = 239.'],answer:'239'},when:'Use whenever the subtrahend is close to a friendly round number.',watch:'“Give back” means add because you deliberately subtracted too much.'}},
 {n:13,title:'Simple Division',start:130,end:140,id:'sm-13',type:'simplediv',learn:{idea:'Divide from left to right using the largest multiplication fact that fits, carrying the remainder into the next digit.',steps:['Begin with the leftmost digit or group of digits large enough for the divisor.','Ask: what whole-number multiple of the divisor is as large as possible without going over?','Write that quotient digit.','Subtract to get the remainder.','Carry the remainder in front of the next digit and repeat.','For decimals, place the decimal in the quotient directly above the decimal in the dividend and continue with zeros as needed.'],example:{problem:'3,721 ÷ 4',work:['37 ÷ 4 = 9 remainder 1.','Carry the 1 to the next digit: 12.','12 ÷ 4 = 3 remainder 0.','1 ÷ 4 = 0 remainder 1.','So 3,721 ÷ 4 = 930 remainder 1 = 930¼.'],answer:'930¼'},when:'Use for ordinary short division, including mental one-line division when the numbers are manageable.',watch:'Never choose a quotient digit whose product with the divisor exceeds the current partial dividend.'}},
 {n:14,title:'Long Division by Factors',start:141,end:148,id:'sm-14',type:'factorsdiv',learn:{idea:'If the divisor factors into easy numbers, divide in stages instead of by the whole divisor at once.',steps:['Factor the divisor into convenient factors.','Divide the dividend by the first factor.','Divide that quotient by the second factor.','Continue if there are more factors.','For decimal accuracy, append enough zeros and one extra digit for rounding.'],example:{problem:'1,488 ÷ 24',work:['24 = 6 × 4.','1,488 ÷ 6 = 248.','248 ÷ 4 = 62.'],answer:'62'},when:'Use when the divisor has small convenient factors such as 12, 18, 20, 24, 28, 36.',watch:'The factors must multiply exactly to the original divisor. Do not round the divisor here.'}},
 {n:15,title:'Standard Long Division Made Easy',start:149,end:156,id:'sm-15',type:'longdiv',learn:{idea:'Estimate quotient digits quickly by simplifying the divisor, then multiply back and correct if necessary.',steps:['At each stage, look at the current partial dividend.','Estimate how many times the divisor fits by rounding or simplifying the divisor.','Multiply your estimated quotient digit by the actual divisor.','If the product is too large, lower the digit; if there is room for another divisor, raise it.','Subtract, bring down the next digit, and repeat.'],example:{problem:'Divide by 29 (book method)',work:['Think of 29 as about 30.','When the current partial dividend is 74, 74 ÷ 30 is a little more than 2.','Try quotient digit 2: 2 × 29 = 58.','74 − 58 = 16; continue with the next digit.'],answer:'Use estimate → multiply back → subtract'},when:'Use when factor-division is not convenient and you need standard long division.',watch:'The rounded divisor is only for estimating the quotient digit; always multiply back with the real divisor.'}},
 {n:16,title:'Direct Long Division',start:157,end:165,id:'sm-16',type:'directdiv',learn:{idea:'Compress long division by rounding the divisor to a friendly nearby number and adjusting the running remainder mentally.',steps:['Round the divisor down or up to an easy multiple of 10.','Record the difference between the true divisor and the rounded divisor.','Estimate quotient digits using the rounded divisor.','Adjust for the difference as each quotient digit is chosen.','Keep a running remainder and continue place by place.'],example:{problem:'231 ÷ 39',work:['Round 39 up to 40; the adjustment is −1 per group compared with 40.','Estimate with 40: about 5 groups in 231.','Because 39 is 1 less than 40, each group actually uses 1 less, leaving 5 more than the 40-based estimate would.','Check the candidate using 39 × 5 = 195, then continue/remainder as needed.'],answer:'5 remainder 36 (before decimal continuation)'},when:'Use only after ordinary long division is secure; this chapter is about reducing written work, not introducing division.',watch:'This is not “round and ignore.” The divisor difference must be compensated.'}},
 {n:17,title:'Checking Answers (Division)',start:166,end:172,id:'sm-17',type:'checkdiv',learn:{idea:'Check division by reversing it into multiplication, then optionally use casting out nines on that multiplication.',steps:['Take quotient × divisor.','Add any remainder.','The result must equal the original dividend.','For large numbers, reduce dividend, divisor and quotient with digit sums/casting out nines as a quick extra check.'],example:{problem:'24 ÷ 6 = 4',work:['Reverse it: 4 × 6 = 24.','Because the reverse multiplication recreates the dividend, the division is consistent.'],answer:'Check passes'},when:'Use after any division, especially when quotient estimation was involved.',watch:'If there is a remainder, the check is quotient × divisor + remainder = dividend.'}},
 {n:18,title:'Fractions Made Easy',start:173,end:184,id:'sm-18',type:'fractions',learn:{idea:'The chapter treats each fraction operation as a distinct rule; learn the meaning first, then the arithmetic shortcut.',steps:['Same denominators: add or subtract numerators and keep the denominator.','Different denominators for addition: cross-multiply to form the new numerator, and multiply denominators for the new denominator; simplify.','Different denominators for subtraction: cross-multiply and subtract the cross-products; multiply denominators; simplify.','Multiplication: numerator × numerator, denominator × denominator; simplify.','Division: invert the divisor fraction, then multiply.','Fraction to decimal: numerator ÷ denominator.'],example:{problem:'2/3 + 3/4',work:['Cross-products: 2×4 = 8 and 3×3 = 9.','Add: 8 + 9 = 17.','Denominator: 3 × 4 = 12.','17/12 = 1 5/12.'],answer:'1 5/12'},when:'Use after Maya understands fractions as equal parts. The chapter is mainly about efficient computation.',watch:'Do not let the shortcut hide fraction meaning. In particular, denominators are not simply added.'}},
 {n:19,title:'Direct Multiplication',start:185,end:194,id:'sm-19',type:'directmult',learn:{idea:'When reference-number multiplication is awkward, use direct partial products—either written right-to-left with carrying or mental left-to-right without carrying.',steps:['For two-digit × two-digit mentally, multiply tens×tens first and keep that subtotal.','Multiply the two cross-products and add them; their place value is tens, so multiply that sum by 10.','Add that to the subtotal.','Multiply units×units and add.','On paper you can instead work right-to-left, carrying after each stage.'],example:{problem:'76 × 34',work:['70 × 30 = 2,100.','Cross-products: 70×4 = 280 and 30×6 = 180; together 460.','2,100 + 460 = 2,560.','6 × 4 = 24.','2,560 + 24 = 2,584.'],answer:'2,584'},when:'Use when the reference-number method is not obviously simpler.',watch:'Keep place value explicit: the cross-product total represents tens. The book’s negative-number variant is optional enrichment, not a prerequisite.'}},
 {n:20,title:'Putting It All into Practice',start:195,end:198,id:'sm-20',type:'mixed',learn:{idea:'Choose the easiest valid method for the numbers in front of you instead of forcing one trick.',steps:['Look at the structure before calculating.','Ask whether the numbers are near a shared reference, near different related references, near a round number for compensation, easy to factor, or better handled directly.','Choose the method with the fewest mental steps.','Estimate first when decimals or large values are involved.','Check the answer when practical.'],example:{problem:'Which method for 48 × 25?',work:['25 is a quarter of 100.','48 × 25 = 48 × 100 ÷ 4.','4,800 ÷ 4 = 1,200.','That is simpler than forcing a reference-number setup.'],answer:'1,200'},when:'Use as mixed review after several methods are genuinely understood.',watch:'Speed is a consequence of choosing an easy structure; it is not the learning goal.'}}
];

const SM_APPENDICES=[
 {label:'A',title:'Using the Methods in the Classroom',page:203,note:'Teaching notes: build confidence, let students explain methods, and practice enough for the structure to become familiar.'},
 {label:'B',title:'Working Through a Problem',page:207,note:'A problem-solving reminder: understand what is asked, identify useful structure, choose a method, then check.'},
 {label:'C',title:'Learn the 13, 14 and 15 Times Tables',page:209,note:'Use the reference-number multiplication ideas rather than memorizing these facts in isolation.'},
 {label:'D',title:'Tests for Divisibility',page:211,note:'Quick tests for deciding whether numbers divide evenly.'},
 {label:'E',title:'Keeping Count',page:215,note:'Finger/mental bookkeeping techniques for holding intermediate results.'},
 {label:'F',title:'Plus and Minus Numbers',page:217,note:'Extension of the signed-number ideas introduced by above/below reference numbers.'},
 {label:'G',title:'Percentages',page:219,note:'Percent as “per hundred,” with efficient calculations based on known fractions and multiples.'},
 {label:'H',title:'Hints for Learning',page:223,note:'Practice and learning advice from the author.'},
 {label:'I',title:'Estimating',page:225,note:'Use rounded values to judge whether an exact answer is plausible.'},
 {label:'J',title:'Squaring Numbers Ending in 5',page:227,note:'Special square pattern for numbers ending in 5.'},
 {label:'K',title:'Practice Sheets',page:231,note:'Source practice pages.'}
];

function smLoad(){try{return JSON.parse(localStorage.getItem(SM_KEY)||'{}')}catch(e){return {}}}
let SMD=smLoad(); if(!SMD.progress)SMD.progress={};
function smSave(){localStorage.setItem(SM_KEY,JSON.stringify(SMD))}
function smProg(id){return SMD.progress[id]||(SMD.progress[id]={level:1,streak:0,attempts:0,mastered:false})}
function smPdf(c){return `/api/lesson-pdf?id=${encodeURIComponent(SM_BOOK.id)}&start=${c.start+SM_BOOK.offset}&end=${c.end+SM_BOOK.offset}`}
function smPages(c){return `Book pp. ${c.start}–${c.end} · PDF pp. ${c.start+SM_BOOK.offset}–${c.end+SM_BOOK.offset}`}
function smR(a,b){return Math.floor(Math.random()*(b-a+1))+a}
function smPick(a){return a[smR(0,a.length-1)]}
function smQ(text,answer,hint=''){return {text,answer,hint}}

function refProduct(a,b,ref){const da=a-ref,db=b-ref;return {main:(a+db)*ref,side:da*db,answer:a*b,da,db};}
function smGen(c,l){
 l=Math.max(1,Math.min(4,l||1));
 switch(c.type){
  case'refbelow':case'reference':{let ref=l<3?10:100, a=ref-smR(1,l<3?4:8), b=ref-smR(1,l<3?4:8);let z=refProduct(a,b,ref);return smQ(`${a} × ${b}`,z.answer,`Reference ${ref}. Shortfalls: ${-z.da} and ${-z.db}. Cross-subtract, ×${ref}, then add the shortfall product.`)}
  case'above':{let ref=l<3?10:100,a=ref+smR(1,l<3?7:15),b=ref+smR(1,l<3?7:15);let z=refProduct(a,b,ref);return smQ(`${a} × ${b}`,z.answer,`Reference ${ref}. Differences +${z.da}, +${z.db}; cross-add, ×${ref}, then add ${z.da}×${z.db}.`)}
  case'mixedref':{let ref=l<3?10:100,a=ref-smR(1,l<3?3:8),b=ref+smR(1,l<3?7:25);let z=refProduct(a,b,ref);return smQ(`${a} × ${b}`,z.answer,`Reference ${ref}. One difference is negative, so the side product is subtracted.`)}
  case'check':{let a=smR(12,99),b=smR(12,99),ans=a*b;return smQ(`Check: ${a} × ${b} = ${ans}`, 'Passes', 'Reduce each factor and the answer by digit sums / casting out nines. Do the substitute multiplication.');}
  case'anyref':{let ref=smPick(l<3?[20,50]:[20,50,200]),a=ref+smR(-4,6),b=ref+smR(-4,6);if(a<=0||b<=0){a=ref+2;b=ref+3}return smQ(`${a} × ${b}`,a*b,`Use reference ${ref}. First decide the easiest way to multiply by ${ref}.`)}
  case'lower':{let n=smR(3,l<3?29:99);return smQ(`${n} × 5`,n*5,'Multiply by 10, then halve.');}
  case'times11':{let n=l<3?smR(12,99):smR(101,9999);return smQ(`${n} × 11`,n*11,'Add neighboring digits; two-digit shortcut: put the digit sum in the middle.');}
  case'decimals':{let a=smR(12,98)/10,b=smR(12,98)/10;let ans=(a*b).toFixed(2).replace(/0+$/,'').replace(/\.$/,'');return smQ(`${a.toFixed(1)} × ${b.toFixed(1)}`,ans,'Ignore decimals, multiply, then restore total decimal places. Estimate the size.');}
  case'tworef':{let a=smPick([8,9,12,13,18,19]), mult=smPick([3,4,5,7,8,9,12]),ref1=a<15?10:20,ref2=ref1*mult,b=ref2+smR(-4,4);if(b<=0)b=ref2-2;return smQ(`${a} × ${b}`,a*b,`Think of references ${ref1} and ${ref2} = ${ref1} × ${mult}.`)}
  case'addition':{let a=smR(20,900),b=smPick([8,9,18,19,38,48,49,85,90,95,98,99]);return smQ(`${a} + ${b}`,a+b,`Round ${b} to a friendly amount, add it, then compensate.`)}
  case'subtraction':{let b=smPick([8,9,18,19,38,57,68,87,185,298]),a=smR(b+20,b+700);return smQ(`${a} − ${b}`,a-b,`Round ${b} up, subtract the friendly number, then give back the difference.`)}
  case'simplediv':{let d=smR(2,9),q=smR(12,999),r=smR(0,d-1),n=d*q+r;return smQ(`${n} ÷ ${d}`,r?`${q} remainder ${r}`:q,'Divide from left to right; carry each remainder into the next digit.');}
  case'factorsdiv':{let d=smPick([12,15,18,20,24,28,36]),q=smR(5,80),n=d*q;return smQ(`${n} ÷ ${d}`,q,`Factor ${d} into easy factors and divide in stages.`)}
  case'longdiv':{let d=smR(21,49),q=smR(12,80),r=smR(0,d-1),n=d*q+r;return smQ(`${n} ÷ ${d}`,r?`${q} remainder ${r}`:q,'Estimate each quotient digit with a rounded divisor; multiply back with the real divisor.');}
  case'directdiv':{let d=smPick([29,31,39,41,49]),q=smR(4,30),r=smR(0,d-1),n=d*q+r;return smQ(`${n} ÷ ${d}`,r?`${q} remainder ${r}`:q,`Round ${d} to the nearest easy ten, but compensate for the difference.`)}
  case'checkdiv':{let d=smR(2,12),q=smR(2,30),r=smR(0,d-1),n=d*q+r;return smQ(`Check: ${n} ÷ ${d} = ${q}${r?` r${r}`:''}`, 'Passes if reverse multiplication returns '+n,`Compute ${q} × ${d}${r?` + ${r}`:''}.`)}
  case'fractions':{let d1=smPick([2,3,4,5,6,7,8]),d2=smPick([2,3,4,5,6,7,8]),n1=smR(1,d1-1),n2=smR(1,d2-1);let num=n1*d2+n2*d1,den=d1*d2,g=(a,b)=>b?g(b,a%b):a,k=g(num,den);return smQ(`${n1}/${d1} + ${n2}/${d2}`,`${num/k}/${den/k}`,'Cross-multiply for the numerator, multiply denominators, then simplify.');}
  case'directmult':{let a=smR(12,99),b=smR(12,99);return smQ(`${a} × ${b}`,a*b,'Mental left-to-right: tens×tens, cross-products×10, units×units.');}
  default:{let choices=['addition','subtraction','ref','factor'];let t=smPick(choices);if(t==='addition'){let a=smR(100,800),b=smPick([98,99,195]);return smQ(`${a}+${b}`,a+b,'Choose compensation.')}if(t==='subtraction'){let a=smR(300,900),b=smPick([98,199,298]);return smQ(`${a}−${b}`,a-b,'Choose compensation.')}if(t==='factor'){let a=smR(12,48),b=25;return smQ(`${a}×25`,a*b,'Think ×100 then ÷4.')}let a=smR(92,99),b=smR(92,99);return smQ(`${a}×${b}`,a*b,'Choose reference 100.');}
 }
}

let SMC=null,SMQ=null;
function renderSpeedMathHome(){
 homeBtn.onclick=renderProfiles;
 screen.innerHTML=`<div class="crumbs"><button class="text-link" id="smb">Math profiles</button><span>›</span><span>Speed Math</span></div><div class="eyebrow">MAYA · BILL HANDLEY</div><h2>Speed Math for Kids</h2><p class="lead">This profile now separates <strong>learning</strong> from <strong>practice</strong>. You should be able to teach the method from this site without opening the book. The source pages are there for reference, not as the explanation.</p><div class="lesson-list">${SM_CHAPTERS.map(c=>{let p=smProg(c.id);return `<button class="lesson-tile" data-sm="${c.id}"><div><strong>${c.n}. ${c.title}</strong><span>${smPages(c)}</span></div><span class="status ${p.mastered?'mastered':''}">${p.mastered?'Secure':p.attempts?`Level ${p.level}`:'Learn'}</span></button>`}).join('')}</div><div class="card"><div class="label">REFERENCE EXTRAS FROM THE BOOK</div>${SM_APPENDICES.map(a=>`<div class="appendix-row"><strong>${a.label}. ${a.title}</strong><span class="mini">p. ${a.page} · ${a.note}</span></div>`).join('')}</div>`;
 document.getElementById('smb').onclick=renderProfiles;screen.querySelectorAll('[data-sm]').forEach(x=>x.onclick=()=>renderSMChapter(x.dataset.sm));
}
function renderSMChapter(id){
 const c=SM_CHAPTERS.find(x=>x.id===id),p=smProg(id);SMC=c;
 screen.innerHTML=`<div class="eyebrow">MAYA · CHAPTER ${c.n}</div><h2>${c.title}</h2><div class="sm-mode-tabs"><button id="smLearn" class="book-tab active">Learning</button><button id="smPractice" class="book-tab">Practice</button></div><div id="smMode"></div>`;
 document.getElementById('smLearn').onclick=()=>renderSMLearn(c);document.getElementById('smPractice').onclick=()=>renderSMPracticeStart(c,p.level);renderSMLearn(c);
}
function setSMTab(mode){document.getElementById('smLearn')?.classList.toggle('active',mode==='learn');document.getElementById('smPractice')?.classList.toggle('active',mode==='practice');}
function renderSMLearn(c){
 setSMTab('learn');const l=c.learn;
 document.getElementById('smMode').innerHTML=`<div class="card soft page-card"><div class="label">SOURCE</div><strong>${smPages(c)}</strong><div class="page-actions"><a class="page-link quiet" href="${smPdf(c)}" target="_blank">Open source pages</a></div></div><div class="learn-summary"><div class="label">THE IDEA</div><p class="script">${l.idea}</p></div><div class="card"><div class="label">HOW TO DO IT</div><ol class="step-list">${l.steps.map(s=>`<li>${s}</li>`).join('')}</ol></div><div class="example-box"><div class="label">WORKED EXAMPLE</div><div class="example-problem">${l.example.problem}</div><ol class="step-list">${l.example.work.map(s=>`<li>${s}</li>`).join('')}</ol><div class="example-answer">Answer: ${l.example.answer}</div></div><div class="card"><div class="label">WHEN THIS METHOD IS USEFUL</div><p class="script">${l.when}</p></div><div class="card warn"><div class="label">WATCH FOR THIS</div><p class="script">${l.watch}</p></div><button id="smReady" class="primary full-touch">Ready to practice</button>`;
 document.getElementById('smReady').onclick=()=>renderSMPracticeStart(c,smProg(c.id).level);
}
function renderSMPracticeStart(c,level){
 setSMTab('practice');const p=smProg(c.id);SMQ=smGen(c,level);
 document.getElementById('smMode').innerHTML=`<div class="practice-top"><div><strong>Level ${p.level}/4</strong><span>${p.streak}/2 confident at this level</span></div>${p.mastered?'<span class="status mastered">Secure</span>':''}</div><div class="question-box"><div class="label">ASK MAYA</div><div class="q">${SMQ.text}</div></div><details class="hint-box"><summary>Show method hint</summary><p>${SMQ.hint}</p></details><details class="answer-box"><summary>Show parent answer</summary><p><strong>${SMQ.answer}</strong></p></details><p class="focus">What happened?</p><div class="outcomes"><button data-smo="confident"><strong>Right + confident</strong></button><button data-smo="help"><strong>Right, but needed help</strong></button><button data-smo="idea"><strong>Answer right, method shaky</strong></button><button data-smo="lost"><strong>Lost track midway</strong></button><button data-smo="different"><strong>Different valid method</strong></button><button data-smo="wrong"><strong>Wrong / unsure</strong></button></div>`;
 document.querySelectorAll('[data-smo]').forEach(x=>x.onclick=()=>renderSMIntervention(x.dataset.smo));
}
function smUp(out){let p=smProg(SMC.id),e='stay';p.attempts++;if(out==='confident'){p.streak++;if(p.streak>=2){if(p.level<4){p.level++;p.streak=0;e='levelup'}else{p.mastered=true;p.streak=0;e='mastered'}}}else p.streak=0;smSave();return e}
function smNext(c){return SM_CHAPTERS[SM_CHAPTERS.findIndex(x=>x.id===c.id)+1]||null}
function renderSMIntervention(out){
 let c=SMC,e=smUp(out),p=smProg(c.id),n=smNext(c),title='',body='',tone='';
 if(out==='confident'){if(e==='mastered'){title='Secure for now';body='She has given two confident answers at Level 4. Stop drilling this method today. Move on and revisit it later in mixed practice.';tone='good'}else if(e==='levelup'){title=`Move to Level ${p.level}`;body='Two confident answers were enough. The next problem keeps the same method but asks for a little more independence or less convenient numbers.';tone='good'}else{title='One confirming question';body='That was confident. Ask one more at this level; two confident answers move her up.'}}
 if(out==='help'){title='Stay on the same level';body='Do another problem with the method steps still visible. Remove only one prompt. Do not increase the number difficulty yet.'}
 if(out==='idea'){title='Go back to Learning';body='The answer is not the goal if the method itself is fuzzy. Reopen the worked example and have Maya narrate what each step is doing before another practice question.';tone='warn'}
 if(out==='lost'){title='Externalize the middle steps';body='Write each intermediate subtotal or adjustment. The mental method should become compressed only after the structure is stable.';tone='warn'}
 if(out==='different'){title='Keep a valid easier method';body='If Maya used a correct, simpler route, keep it. Ask why it works. Then compare Handley’s method as an optional second tool rather than replacing her method.'}
 if(out==='wrong'){title='Find the first broken step';body='Return to the Learning tab and check the method one line at a time: reference/rounding choice → first transformation → place value/sign → final adjustment. Practice only the first step that fails.';tone='warn'}
 const meter=p.mastered?`<div class="mastery-box"><strong>Done for today.</strong><span>This chapter is secure for now.</span></div>`:`<div class="mastery-line"><strong>Level ${p.level}/4</strong><span>${p.streak}/2 confident answers</span></div>`;
 document.getElementById('smMode').innerHTML=`${meter}<div class="result ${tone}"><div class="route-title">${title}</div><p class="route-copy">${body}</p></div><div class="toolbar">${p.mastered&&n?`<button id="smNext" class="primary">Next chapter: ${n.title}</button>`:`<button id="smAgain" class="primary">${e==='levelup'?`Try Level ${p.level}`:'Another practice question'}</button>`}<button id="smLearnAgain" class="secondary">Learning section</button></div>`;
 const ag=document.getElementById('smAgain');if(ag)ag.onclick=()=>renderSMPracticeStart(c,p.level);const nx=document.getElementById('smNext');if(nx)nx.onclick=()=>renderSMChapter(n.id);document.getElementById('smLearnAgain').onclick=()=>renderSMLearn(c);
}
window.renderSpeedMathHome=renderSpeedMathHome;
